/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2024-07-17 01:31:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.system;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class comncod_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1717304976992L));
    _jspx_dependants.put("jar:file:/C:/Users/user/git/egov/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/scm/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<title>Job Korea :: 공통 코드 관리</title>\r\n");
      out.write("<!-- sweet alert import -->\r\n");
      out.write("<script src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CTX_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/sweetalert/sweetalert.min.js'></script>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/common_include.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- sweet swal import -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t// 그룹코드 페이징 설정\r\n");
      out.write("\tvar pageSizeComnGrpCod = 5;\r\n");
      out.write("\tvar pageBlockSizeComnGrpCod = 5;\r\n");
      out.write("\t\r\n");
      out.write("\t// 상세코드 페이징 설정\r\n");
      out.write("\tvar pageSizeComnDtlCod = 5;\r\n");
      out.write("\tvar pageBlockSizeComnDtlCod = 10;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** OnLoad event */ \r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\r\n");
      out.write("\t\t// 그룹코드 조회\r\n");
      out.write("\t\tfListComnGrpCod();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 버튼 이벤트 등록\r\n");
      out.write("\t\tfRegisterButtonClickEvent();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t/** 버튼 이벤트 등록 */\r\n");
      out.write("\tfunction fRegisterButtonClickEvent() {\r\n");
      out.write("\t\t$('a[name=btn]').click(function(e) {\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar btnId = $(this).attr('id');\r\n");
      out.write("\r\n");
      out.write("\t\t\tswitch (btnId) {\r\n");
      out.write("\t\t\t\tcase 'btnSaveGrpCod' :\r\n");
      out.write("\t\t\t\t\tfSaveGrpCod();\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase 'btnDeleteGrpCod' :\r\n");
      out.write("\t\t\t\t\tfDeleteGrpCod();\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase 'btnSaveDtlCod' :\r\n");
      out.write("\t\t\t\t\tfSaveDtlCod();\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase 'btnDeleteDtlCod' :\r\n");
      out.write("\t\t\t\t\tfDeleteDtlCod();\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase 'btnSearchGrpcod':\r\n");
      out.write("\t\t\t\t\tboard_search();\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase 'btnCloseGrpCod' :\r\n");
      out.write("\t\t\t\tcase 'btnCloseDtlCod' :\r\n");
      out.write("\t\t\t\t\tgfCloseModal();\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 그룹코드 폼 초기화 */\r\n");
      out.write("\tfunction fInitFormGrpCod(object) {\r\n");
      out.write("\t\t$(\"#grp_cod\").focus();\r\n");
      out.write("\t\tif( object == \"\" || object == null || object == undefined) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#grp_cod\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#grp_cod_nm\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#grp_cod_eplti\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#grp_tmp_fld_01\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#grp_tmp_fld_02\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#grp_tmp_fld_03\").val(\"\");\r\n");
      out.write("\t\t\t$(\"input:radio[name=grp_use_poa]:input[value='Y']\").attr(\"checked\", true);\r\n");
      out.write("\t\t\t$(\"#grp_cod\").attr(\"readonly\", false);\r\n");
      out.write("\t\t\t$(\"#grp_cod\").css(\"background\", \"#FFFFFF\");\r\n");
      out.write("\t\t\t$(\"#grp_cod\").focus();\r\n");
      out.write("\t\t\t$(\"#btnDeleteGrpCod\").hide();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#grp_cod\").val(object.grp_cod);\r\n");
      out.write("\t\t\t$(\"#grp_cod_nm\").val(object.grp_cod_nm);\r\n");
      out.write("\t\t\t$(\"#grp_cod_eplti\").val(object.grp_cod_eplti);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#grp_tmp_fld_01\").val(object.tmp_fld_01);\r\n");
      out.write("\t\t\t$(\"#grp_tmp_fld_02\").val(object.tmp_fld_02);\r\n");
      out.write("\t\t\t$(\"#grp_tmp_fld_03\").val(object.tmp_fld_03);\r\n");
      out.write("\t\t\t$(\"input:radio[name=grp_use_poa]:input[value=\"+object.use_poa+\"]\").attr(\"checked\", true);\r\n");
      out.write("\t\t\t$(\"#grp_cod\").attr(\"readonly\", true);\r\n");
      out.write("\t\t\t$(\"#grp_cod\").css(\"background\", \"#F5F5F5\");\r\n");
      out.write("\t\t\t$(\"#grp_cod_nm\").focus();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(object.tmp_fld_01>0){\r\n");
      out.write("\t\t\t\t$(\"#btnDeleteGrpCod\").hide();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\"#btnDeleteGrpCod\").show();\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 검색기능\r\n");
      out.write("\tfunction board_search(currentPage) {\r\n");
      out.write("        \r\n");
      out.write("        var sname = $('#sname');\r\n");
      out.write("        var searchKey = document.getElementById(\"searchKey\");\r\n");
      out.write("\t\tvar oname = searchKey.options[searchKey.selectedIndex].value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcurrentPage = currentPage || 1;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tconsole.log(\"currentPage : \" + currentPage);     \r\n");
      out.write("\t\t\r\n");
      out.write("        var param = {\r\n");
      out.write("        \t\t  sname : sname.val()\r\n");
      out.write("        \t  ,\t  oname : oname\r\n");
      out.write("              ,   currentPage : currentPage\r\n");
      out.write("              ,   pageSize : pageSizeComnGrpCod\r\n");
      out.write("        }\r\n");
      out.write("        //swal(JSON.stringify(param));\r\n");
      out.write("        var resultCallback = function(data) {\r\n");
      out.write("        \tflistGrpCodResult(data, currentPage); \r\n");
      out.write("        };\r\n");
      out.write("        \r\n");
      out.write("        callAjax(\"/system/listComnGrpCod.do\", \"post\", \"text\", true, param, resultCallback);\r\n");
      out.write("        \r\n");
      out.write("  } \r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t/** 상세코드 폼 초기화 */\r\n");
      out.write("\tfunction fInitFormDtlCod(object) {\r\n");
      out.write("\r\n");
      out.write("\t\tvar grpCod = $(\"#tmpGrpCod\").val();\r\n");
      out.write("\t\tvar grpCodNm = $(\"#tmpGrpCodNm\").val();\r\n");
      out.write("\r\n");
      out.write("\t\tif( object == \"\" || object == null || object == undefined) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#dtl_grp_cod\").val(grpCod);\r\n");
      out.write("\t\t\t$(\"#dtl_grp_cod_nm\").val(grpCodNm);\r\n");
      out.write("\t\t\t$(\"#dtl_cod\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#dtl_cod_nm\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#dtl_odr\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#dtl_cod_eplti\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#dtl_tmp_fld_01\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#dtl_tmp_fld_02\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#dtl_tmp_fld_03\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#dtl_tmp_fld_04\").val(\"\");\r\n");
      out.write("\t\t\t$(\"input:radio[name=dtl_use_poa]:input[value='Y']\").attr(\"checked\", true);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#dtl_grp_cod\").attr(\"readonly\", true);\r\n");
      out.write("\t\t\t$(\"#dtl_grp_cod\").css(\"background\", \"#F5F5F5\");\r\n");
      out.write("\t\t\t$(\"#dtl_grp_cod_nm\").attr(\"readonly\", true);\r\n");
      out.write("\t\t\t$(\"#dtl_grp_cod_nm\").css(\"background\", \"#F5F5F5\");\r\n");
      out.write("\t\t\t$(\"#dtl_cod\").attr(\"readonly\", false);\r\n");
      out.write("\t\t\t$(\"#dtl_cod\").css(\"background\", \"#FFFFFF\");\r\n");
      out.write("\t\t\t$(\"#btnDeleteDtlCod\").hide();\r\n");
      out.write("\t\t\t$(\"#dtl_cod\").focus();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#dtl_grp_cod\").val(object.grp_cod);\r\n");
      out.write("\t\t\t$(\"#dtl_grp_cod_nm\").val(object.grp_cod_nm);\r\n");
      out.write("\t\t\t$(\"#dtl_cod\").val(object.dtl_cod);\r\n");
      out.write("\t\t\t$(\"#dtl_cod_nm\").val(object.dtl_cod_nm);\r\n");
      out.write("\t\t\t$(\"#dtl_odr\").val(object.odr);\r\n");
      out.write("\t\t\t$(\"#dtl_cod_eplti\").val(object.dtl_cod_eplti);\r\n");
      out.write("\t\t\t$(\"#dtl_tmp_fld_01\").val(object.tmp_fld_01);\r\n");
      out.write("\t\t\t$(\"#dtl_tmp_fld_02\").val(object.tmp_fld_02);\r\n");
      out.write("\t\t\t$(\"#dtl_tmp_fld_03\").val(object.tmp_fld_03);\r\n");
      out.write("\t\t\t$(\"#dtl_tmp_fld_04\").val(object.tmp_fld_04);\r\n");
      out.write("\t\t\t$(\"input:radio[name=dtl_use_poa]:input[value='\"+object.use_poa+\"']\").attr(\"checked\", true);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#dtl_grp_cod\").attr(\"readonly\", true);\r\n");
      out.write("\t\t\t$(\"#dtl_grp_cod\").css(\"background\", \"#F5F5F5\");\r\n");
      out.write("\t\t\t$(\"#dtl_grp_cod_nm\").attr(\"readonly\", true);\r\n");
      out.write("\t\t\t$(\"#dtl_grp_cod_nm\").css(\"background\", \"#F5F5F5\");\r\n");
      out.write("\t\t\t$(\"#dtl_cod\").attr(\"readonly\", true);\r\n");
      out.write("\t\t\t$(\"#dtl_cod\").css(\"background\", \"#F5F5F5\");\r\n");
      out.write("\t\t\t$(\"#btnDeleteDtlCod\").show();\r\n");
      out.write("\t\t\t$(\"#dtl_cod_nm\").focus();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 그룹코드 저장 validation */\r\n");
      out.write("\tfunction fValidateGrpCod() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar chk = checkNotEmpty(\r\n");
      out.write("\t\t\t\t[\r\n");
      out.write("\t\t\t\t\t\t[ \"grp_cod\", \"그룹 코드를 입력해 주세요.\" ]\r\n");
      out.write("\t\t\t\t\t,\t[ \"grp_cod_nm\", \"그룹 코드 명을 입력해 주세요\" ]\r\n");
      out.write("\t\t\t\t\t,\t[ \"grp_cod_eplti\", \"그룹 코드 설명을 입력해 주세요.\" ]\r\n");
      out.write("\t\t\t\t]\r\n");
      out.write("\t\t);\r\n");
      out.write("\r\n");
      out.write("\t\tif (!chk) {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 상세코드 저장 validation */\r\n");
      out.write("\tfunction fValidateDtlCod() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar chk = checkNotEmpty(\r\n");
      out.write("\t\t\t\t[\r\n");
      out.write("\t\t\t\t\t\t[ \"dtl_grp_cod\", \"그룹 코드를 선택해 주세요.\" ]\r\n");
      out.write("\t\t\t\t\t,\t[ \"dtl_cod\", \"상세 코드를 입력해 주세요.\" ]\r\n");
      out.write("\t\t\t\t\t,\t[ \"dtl_cod_nm\", \"상세 코드 명을 입력해 주세요\" ]\r\n");
      out.write("\t\t\t\t\t,\t[ \"dtl_cod_eplti\", \"상세 코드 설명을 입력해 주세요.\" ]\r\n");
      out.write("\t\t\t\t\t,\t[ \"dtl_odr\", \"상세 코드 설명을 입력해 주세요.\" ]\r\n");
      out.write("\t\t\t\t]\r\n");
      out.write("\t\t);\r\n");
      out.write("\r\n");
      out.write("\t\tif (!chk) {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 그룹코드 모달 실행 */\r\n");
      out.write("\tfunction fPopModalComnGrpCod(grp_cod) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 신규 저장\r\n");
      out.write("\t\tif (grp_cod == null || grp_cod==\"\") {\r\n");
      out.write("\t\t\t//swal(\"여기도 찍어봅세  \");\r\n");
      out.write("\t\t\t// Tranjection type 설정\r\n");
      out.write("\t\t\t$(\"#action\").val(\"I\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 그룹코드 폼 초기화\r\n");
      out.write("\t\t\tfInitFormGrpCod();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 모달 팝업\r\n");
      out.write("\t\t\tgfModalPop(\"#layer1\");\r\n");
      out.write("\r\n");
      out.write("\t\t// 수정 저장\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t// Tranjection type 설정\r\n");
      out.write("\t\t\t$(\"#action\").val(\"U\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 그룹코드 단건 조회\r\n");
      out.write("\t\t\tfSelectGrpCod(grp_cod);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 그룹코드 조회 */\r\n");
      out.write("\tfunction fListComnGrpCod(currentPage) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcurrentPage = currentPage || 1;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar sname = $('#sname');\r\n");
      out.write("        var searchKey = document.getElementById(\"searchKey\");\r\n");
      out.write("\t\tvar oname = searchKey.options[searchKey.selectedIndex].value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tconsole.log(\"currentPage : \" + currentPage);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar param = {\t\r\n");
      out.write("\t\t\t\t\tsname : sname.val()\r\n");
      out.write("\t\t\t\t,\toname : oname\r\n");
      out.write("\t\t\t\t,\tcurrentPage : currentPage\r\n");
      out.write("\t\t\t\t,\tpageSize : pageSizeComnGrpCod\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar resultCallback = function(data) {\r\n");
      out.write("\t\t\tflistGrpCodResult(data, currentPage);\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t//Ajax실행 방식\r\n");
      out.write("\t\t//callAjax(\"Url\",type,return,async or sync방식,넘겨준거,값,Callback함수 이름)\r\n");
      out.write("\t\tcallAjax(\"/system/listComnGrpCod.do\", \"post\", \"text\", true, param, resultCallback);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 그룹코드 조회 콜백 함수 */\r\n");
      out.write("\tfunction flistGrpCodResult(data, currentPage) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//swal(data);\r\n");
      out.write("\t\tconsole.log(data);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 기존 목록 삭제\r\n");
      out.write("\t\t$('#listComnGrpCod').empty();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 신규 목록 생성\r\n");
      out.write("\t\t$(\"#listComnGrpCod\").append(data);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 총 개수 추출\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar totalCntComnGrpCod = $(\"#totalCntComnGrpCod\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//swal(totalCntComnGrpCod);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 페이지 네비게이션 생성\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar paginationHtml = getPaginationHtml(currentPage, totalCntComnGrpCod, pageSizeComnGrpCod, pageBlockSizeComnGrpCod, 'fListComnGrpCod');\r\n");
      out.write("\t\tconsole.log(\"paginationHtml : \" + paginationHtml);\r\n");
      out.write("\t\t//swal(paginationHtml);\r\n");
      out.write("\t\t$(\"#comnGrpCodPagination\").empty().append( paginationHtml );\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 현재 페이지 설정\r\n");
      out.write("\t\t$(\"#currentPageComnGrpCod\").val(currentPage);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 그룹코드 단건 조회 */\r\n");
      out.write("\tfunction fSelectGrpCod(grp_cod) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar param = { grp_cod : grp_cod };\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar resultCallback = function(data) {\r\n");
      out.write("\t\t\tfSelectGrpCodResult(data);\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcallAjax(\"/system/selectComnGrpCod.do\", \"post\", \"json\", true, param, resultCallback);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 그룹코드 단건 조회 콜백 함수*/\r\n");
      out.write("\tfunction fSelectGrpCodResult(data) {\r\n");
      out.write("\r\n");
      out.write("\t\tif (data.result == \"SUCCESS\") {\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 모달 팝업\r\n");
      out.write("\t\t\tgfModalPop(\"#layer1\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 그룹코드 폼 데이터 설정\r\n");
      out.write("\t\t\tfInitFormGrpCod(data.comnGrpCodModel);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tswal(data.resultMsg);\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 그룹코드 저장 */\r\n");
      out.write("\tfunction fSaveGrpCod() {\r\n");
      out.write("\r\n");
      out.write("\t\t// vaildation 체크\r\n");
      out.write("\t\tif ( ! fValidateGrpCod() ) {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar resultCallback = function(data) {\r\n");
      out.write("\t\t\tfSaveGrpCodResult(data);\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcallAjax(\"/system/saveComnGrpCod.do\", \"post\", \"json\", true, $(\"#myForm\").serialize(), resultCallback);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 그룹코드 저장 콜백 함수 */\r\n");
      out.write("\tfunction fSaveGrpCodResult(data) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 목록 조회 페이지 번호\r\n");
      out.write("\t\tvar currentPage = \"1\";\r\n");
      out.write("\t\tif ($(\"#action\").val() != \"I\") {\r\n");
      out.write("\t\t\tcurrentPage = $(\"#currentPageComnGrpCod\").val();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (data.result == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 응답 메시지 출력\r\n");
      out.write("\t\t\tswal(data.resultMsg);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 모달 닫기\r\n");
      out.write("\t\t\tgfCloseModal();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 목록 조회\r\n");
      out.write("\t\t\tfListComnGrpCod(currentPage);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t// 오류 응답 메시지 출력\r\n");
      out.write("\t\t\tswal(data.resultMsg);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 입력폼 초기화\r\n");
      out.write("\t\tfInitFormGrpCod();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t/** 그룹코드 삭제 */\r\n");
      out.write("\tfunction fDeleteGrpCod() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tswal(\"정말 삭제하겠습니까? \\n삭제시 복구불가합니다.\", {\r\n");
      out.write("\t\t\t  buttons:{\r\n");
      out.write("\t\t\t\t  yes : \"예\",\r\n");
      out.write("\t\t\t\t  no : \"아니오\"\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t\t}).then((value) => {  /* 이건 이클립스가 게을러서 뜨는 에러!  */\r\n");
      out.write("\t\t\t\tswitch(value){\r\n");
      out.write("\t\t\t\tcase \"yes\":\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar resultCallback = function(data) {\r\n");
      out.write("\t\t\t\t\tfDeleteGrpCodResult(data);\r\n");
      out.write("\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\tcallAjax(\"/system/deleteComnGrpCod.do\", \"post\", \"json\", true, $(\"#myForm\").serialize(), resultCallback);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"no\": \r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 그룹코드 삭제 콜백 함수 */\r\n");
      out.write("\tfunction fDeleteGrpCodResult(data) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar currentPage = $(\"#currentPageComnGrpCod\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (data.result == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 응답 메시지 출력\r\n");
      out.write("\t\t\tswal(data.resultMsg);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 모달 닫기\r\n");
      out.write("\t\t\tgfCloseModal();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 그룹코드 목록 조회\r\n");
      out.write("\t\t\tfListComnGrpCod(currentPage);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tswal(data.resultMsg);\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 상세코드 모달 실행 */\r\n");
      out.write("\tfunction fPopModalComnDtlCod(grp_cod, dtl_cod) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 신규 저장\r\n");
      out.write("\t\tif (dtl_cod == null || dtl_cod==\"\") {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tif ($(\"#tmpGrpCod\").val() == \"\") {\r\n");
      out.write("\t\t\t\tswal(\"그룹 코드를 선택해 주세요.\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// Tranjection type 설정\r\n");
      out.write("\t\t\t$(\"#action\").val(\"I\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 상세코드 폼 초기화\r\n");
      out.write("\t\t\tfInitFormDtlCod();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 모달 팝업\r\n");
      out.write("\t\t\tgfModalPop(\"#layer2\");\r\n");
      out.write("\r\n");
      out.write("\t\t// 수정 저장\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// Tranjection type 설정\r\n");
      out.write("\t\t\t$(\"#action\").val(\"U\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 상세코드 단건 조회\r\n");
      out.write("\t\t\tfSelectDtlCod(grp_cod, dtl_cod);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 상세코드 목록 조회 */\r\n");
      out.write("\tfunction fListComnDtlCod(currentPage, grp_cod, grp_cod_nm) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcurrentPage = currentPage || 1;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 그룹코드 정보 설정\r\n");
      out.write("\t\t$(\"#tmpGrpCod\").val(grp_cod);\r\n");
      out.write("\t\t$(\"#tmpGrpCodNm\").val(grp_cod_nm);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar param = {\r\n");
      out.write("\t\t\t\t\tgrp_cod : grp_cod\r\n");
      out.write("\t\t\t\t,\tcurrentPage : currentPage\r\n");
      out.write("\t\t\t\t,\tpageSize : pageSizeComnDtlCod\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar resultCallback = function(data) {\r\n");
      out.write("\t\t\tflistDtlCodResult(data, currentPage);\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcallAjax(\"/system/listComnDtlCod.do\", \"post\", \"text\", true, param, resultCallback);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 상세코드 조회 콜백 함수 */\r\n");
      out.write("\tfunction flistDtlCodResult(data, currentPage) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 기존 목록 삭제\r\n");
      out.write("\t\t$('#listComnDtlCod').empty(); \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar $data = $( $(data).html() );\r\n");
      out.write("\r\n");
      out.write("\t\t// 신규 목록 생성\r\n");
      out.write("\t\tvar $listComnDtlCod = $data.find(\"#listComnDtlCod\");\t\t\r\n");
      out.write("\t\t$(\"#listComnDtlCod\").append($listComnDtlCod.children());\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 총 개수 추출\r\n");
      out.write("\t\tvar $totalCntComnDtlCod = $data.find(\"#totalCntComnDtlCod\");\r\n");
      out.write("\t\tvar totalCntComnDtlCod = $totalCntComnDtlCod.text(); \r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 페이지 네비게이션 생성\r\n");
      out.write("\t\tvar grp_cod = $(\"#tmpGrpCod\").val();\r\n");
      out.write("\t\tvar grp_cod_nm = $(\"#tmpGrpCodNm\").val();\r\n");
      out.write("\t\tvar paginationHtml = getPaginationHtml(currentPage, totalCntComnDtlCod, pageSizeComnDtlCod, pageBlockSizeComnDtlCod, 'fListComnDtlCod', [grp_cod]);\r\n");
      out.write("\t\t$(\"#comnDtlCodPagination\").empty().append( paginationHtml );\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 현재 페이지 설정\r\n");
      out.write("\t\t$(\"#currentPageComnDtlCod\").val(currentPage);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 상세코드 단건 조회 */\r\n");
      out.write("\tfunction fSelectDtlCod(grp_cod, dtl_cod) {\r\n");
      out.write("\r\n");
      out.write("\t\tvar param = {\r\n");
      out.write("\t\t\t\t\tgrp_cod : grp_cod\r\n");
      out.write("\t\t\t\t,\tdtl_cod : dtl_cod\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar resultCallback = function(data) {\r\n");
      out.write("\t\t\tfSelectDtlCodResult(data);\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcallAjax(\"/system/selectComnDtlCod.do\", \"post\", \"json\", true, param, resultCallback);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 상세코드 단건 조회 콜백 함수*/\r\n");
      out.write("\tfunction fSelectDtlCodResult(data) {\r\n");
      out.write("\r\n");
      out.write("\t\tif (data.result == \"SUCCESS\") {\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 모달 팝업\r\n");
      out.write("\t\t\tgfModalPop(\"#layer2\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 그룹코드 폼 데이터 설정\r\n");
      out.write("\t\t\tfInitFormDtlCod(data.comnDtlCodModel);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tswal(data.resultMsg);\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 상세코드 저장 */\r\n");
      out.write("\tfunction fSaveDtlCod() {\r\n");
      out.write("\r\n");
      out.write("\t\t// vaildation 체크\r\n");
      out.write("\t\tif ( ! fValidateDtlCod() ) {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar resultCallback = function(data) {\r\n");
      out.write("\t\t\tfSaveDtlCodResult(data);\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcallAjax(\"/system/saveComnDtlCod.do\", \"post\", \"json\", true, $(\"#myForm\").serialize(), resultCallback);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 상세코드 저장 콜백 함수 */\r\n");
      out.write("\tfunction fSaveDtlCodResult(data) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 목록 조회 페이지 번호\r\n");
      out.write("\t\tvar currentPage = \"1\";\r\n");
      out.write("\t\tif ($(\"#action\").val() != \"I\") {\r\n");
      out.write("\t\t\tcurrentPage = $(\"#currentPageComnDtlCod\").val();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (data.result == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 응답 메시지 출력\r\n");
      out.write("\t\t\tswal(data.resultMsg);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 모달 닫기\r\n");
      out.write("\t\t\tgfCloseModal();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 목록 조회\r\n");
      out.write("\t\t\tvar grp_cod = $(\"#tmpGrpCod\").val();\r\n");
      out.write("\t\t\tvar grp_cod_nm = $(\"#tmpGrpCodNm\").val();\r\n");
      out.write("\t\t\tfListComnDtlCod(currentPage, grp_cod, grp_cod_nm);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t// 오류 응답 메시지 출력\r\n");
      out.write("\t\t\tswal(data.resultMsg);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 입력폼 초기화\r\n");
      out.write("\t\tfInitFormDtlCod();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 상세코드 삭제 */\r\n");
      out.write("\tfunction fDeleteDtlCod() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar resultCallback = function(data) {\r\n");
      out.write("\t\t\tfDeleteDtlCodResult(data);\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcallAjax(\"/system/deleteComnDtlCod.do\", \"post\", \"json\", true, $(\"#myForm\").serialize(), resultCallback);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/** 상세코드 삭제 콜백 함수 */\r\n");
      out.write("\tfunction fDeleteDtlCodResult(data) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar currentPage = $(\"#currentPageComnDtlCod\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (data.result == \"SUCCESS\") {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 응답 메시지 출력\r\n");
      out.write("\t\t\tswal(data.resultMsg);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 모달 닫기\r\n");
      out.write("\t\t\tgfCloseModal();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 그룹코드 목록 조회\r\n");
      out.write("\t\t\tvar grp_cod = $(\"#tmpGrpCod\").val();\r\n");
      out.write("\t\t\tvar grp_cod_nm = $(\"#tmpGrpCodNm\").val();\r\n");
      out.write("\t\t\tfListComnDtlCod(currentPage, grp_cod, grp_cod_nm);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tswal(data.resultMsg);\r\n");
      out.write("\t\t}\t\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form id=\"myForm\" action=\"\"  method=\"\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"currentPageComnGrpCod\" value=\"1\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"currentPageComnDtlCod\" value=\"1\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"tmpGrpCod\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"tmpGrpCodNm\" value=\"\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"action\" id=\"action\" value=\"\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 모달 배경 -->\r\n");
      out.write("\t<div id=\"mask\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"wrap_area\">\r\n");
      out.write("\r\n");
      out.write("\t\t<h2 class=\"hidden\">header 영역</h2>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<h2 class=\"hidden\">컨텐츠 영역</h2>\r\n");
      out.write("\t\t<div id=\"container\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"lnb\">\r\n");
      out.write("\t\t\t\t\t<!-- lnb 영역 --> ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/lnbMenu.jsp", out, false);
      out.write(" <!--// lnb 영역 -->\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"contents\">\r\n");
      out.write("\t\t\t\t\t<!-- contents -->\r\n");
      out.write("\t\t\t\t\t<h3 class=\"hidden\">contents 영역</h3> <!-- content -->\r\n");
      out.write("\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p class=\"Location\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"../dashboard/dashboard.do\" class=\"btn_set home\">메인으로</a> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn_nav bold\">기준정보</span> <span class=\"btn_nav bold\">공통코드\r\n");
      out.write("\t\t\t\t\t\t\t\t관리</span> <a href=\"../system/comnCodMgr.do\" class=\"btn_set refresh\">새로고침</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p class=\"conTitle\">\r\n");
      out.write("\t\t\t\t\t\t\t<span>그룹 코드</span> <span class=\"fr\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btnType blue\" href=\"javascript:fPopModalComnGrpCod();\" name=\"modal\"><span>신규등록</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"divComGrpCodList\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"6%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"17%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">순번</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">그룹코드</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">그룹코드명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">그룹코드 설명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">사용여부</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">등록일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">비고</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody id=\"listComnGrpCod\"></tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"paging_area\"  id=\"comnGrpCodPagination\"> </div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<table style=\"margin-top: 10px\" width=\"100%\" cellpadding=\"5\" cellspacing=\"0\" border=\"1\"\r\n");
      out.write("                        align=\"left\"\r\n");
      out.write("                        style=\"collapse; border: 1px #50bcdf;\">\r\n");
      out.write("                        <tr style=\"border: 0px; border-color: blue\">\r\n");
      out.write("                           <td width=\"80\" height=\"25\" style=\"font-size: 120%;\">&nbsp;&nbsp;</td>\r\n");
      out.write("                           <td width=\"50\" height=\"25\" style=\"font-size: 100%; text-align:left; padding-right:25px;\">\r\n");
      out.write("     \t                      <select id=\"searchKey\" name=\"searchKey\" style=\"width: 150px;\" v-model=\"searchKey\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"grp_cod\" >그룹코드</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"grp_cod_nm\" >그룹코드명</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("     \t                       <input type=\"text\" style=\"width: 300px; height: 25px;\" id=\"sname\" name=\"sname\">                    \r\n");
      out.write("\t                           <a href=\"\" class=\"btnType blue\" id=\"btnSearchGrpcod\" name=\"btn\"><span>검  색</span></a>\r\n");
      out.write("                           </td> \r\n");
      out.write("                           \r\n");
      out.write("                        </tr>\r\n");
      out.write("                     </table> \r\n");
      out.write("                     \r\n");
      out.write("\t\t\t\t\t\t<p class=\"conTitle mt50\">\r\n");
      out.write("\t\t\t\t\t\t\t<span>상세 코드</span> <span class=\"fr\"> <a\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btnType blue\"  href=\"javascript:fPopModalComnDtlCod();\" name=\"modal\"><span>신규등록</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"divComDtlCodList\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"6%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"5%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"5%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">순번</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">그룹코드</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">상세코드</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">상세코드명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">상세코드 설명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">사용여부</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">비고</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody id=\"listComnDtlCod\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"12\">그룹코드를 선택해 주세요.</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"paging_area\"  id=\"comnDtlCodPagination\"> </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div> <!--// content -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<h3 class=\"hidden\">풋터 영역</h3>\r\n");
      out.write("\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 모달팝업 -->\r\n");
      out.write("\t<div id=\"layer1\" class=\"layerPop layerType2\" style=\"width: 600px;\">\r\n");
      out.write("\t\t<dl>\r\n");
      out.write("\t\t\t<dt>\r\n");
      out.write("\t\t\t\t<strong>그룹코드 관리</strong>\r\n");
      out.write("\t\t\t</dt>\r\n");
      out.write("\t\t\t<dd class=\"content\">\r\n");
      out.write("\t\t\t\t<!-- s : 여기에 내용입력 -->\r\n");
      out.write("\t\t\t\t<table class=\"row\">\r\n");
      out.write("\t\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col width=\"120px\">\r\n");
      out.write("\t\t\t\t\t\t<col width=\"*\">\r\n");
      out.write("\t\t\t\t\t\t<col width=\"120px\">\r\n");
      out.write("\t\t\t\t\t\t<col width=\"*\">\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">그룹 코드 <span class=\"font_red\">*</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" class=\"inputTxt p100\" name=\"grp_cod\" id=\"grp_cod\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">그룹 코드 명 <span class=\"font_red\">*</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" class=\"inputTxt p100\" name=\"grp_cod_nm\" id=\"grp_cod_nm\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">코드 설명 <span class=\"font_red\">*</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" class=\"inputTxt p100\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"grp_cod_eplti\" id=\"grp_cod_eplti\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">사용 유무 <span class=\"font_red\">*</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"radio\" id=\"radio1-1\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"grp_use_poa\" id=\"grp_use_poa_1\" value='Y' /> <label for=\"radio1-1\">사용</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp; <input type=\"radio\" id=\"radio1-2\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"grp_use_poa\" id=\"grp_use_poa_2\" value=\"N\" /> <label for=\"radio1-2\">미사용</label></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- e : 여기에 내용입력 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"btn_areaC mt30\">\r\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"btnType blue\" id=\"btnSaveGrpCod\" name=\"btn\"><span>저장</span></a> \r\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"btnType blue\" id=\"btnDeleteGrpCod\" name=\"btn\"><span>삭제</span></a> \r\n");
      out.write("\t\t\t\t\t<a href=\"\"\tclass=\"btnType gray\"  id=\"btnCloseGrpCod\" name=\"btn\"><span>취소</span></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t\t<a href=\"\" class=\"closePop\"><span class=\"hidden\">닫기</span></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"layer2\" class=\"layerPop layerType2\" style=\"width: 600px;\">\r\n");
      out.write("\t\t<dl>\r\n");
      out.write("\t\t\t<dt>\r\n");
      out.write("\t\t\t\t<strong>상세코드 관리</strong>\r\n");
      out.write("\t\t\t</dt>\r\n");
      out.write("\t\t\t<dd class=\"content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- s : 여기에 내용입력 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<table class=\"row\">\r\n");
      out.write("\t\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col width=\"120px\">\r\n");
      out.write("\t\t\t\t\t\t<col width=\"*\">\r\n");
      out.write("\t\t\t\t\t\t<col width=\"120px\">\r\n");
      out.write("\t\t\t\t\t\t<col width=\"*\">\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">그룹 코드 ID <span class=\"font_red\">*</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" class=\"inputTxt p100\" id=\"dtl_grp_cod\" name=\"dtl_grp_cod\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">그룹 코드 명 <span class=\"font_red\">*</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" class=\"inputTxt p100\" id=\"dtl_grp_cod_nm\" name=\"dtl_grp_cod_nm\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">상세 코드 ID <span class=\"font_red\">*</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" class=\"inputTxt p100\" id=\"dtl_cod\" name=\"dtl_cod\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">상세 코드 명 <span class=\"font_red\">*</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" class=\"inputTxt p100\" id=\"dtl_cod_nm\" name=\"dtl_cod_nm\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">코드 설명</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" class=\"inputTxt p100\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"dtl_cod_eplti\" name=\"dtl_cod_eplti\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">사용 유무 <span class=\"font_red\">*</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"radio\" id=\"dtl_use_poa_1\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"dtl_use_poa\" value=\"Y\" /> <label for=\"radio1-1\">사용</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp; <input type=\"radio\" id=\"dtl_use_poa_2\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"dtl_use_poa\" value=\"N\" /> <label for=\"radio1-2\">미사용</label></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- e : 여기에 내용입력 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"btn_areaC mt30\">\r\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"btnType blue\" id=\"btnSaveDtlCod\" name=\"btn\"><span>저장</span></a>\r\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"btnType blue\" id=\"btnDeleteDtlCod\" name=\"btn\"><span>삭제</span></a>  \r\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"btnType gray\" id=\"btnCloseDtlCod\" name=\"btn\"><span>취소</span></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t\t<a href=\"\" class=\"closePop\"><span class=\"hidden\">닫기</span></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--// 모달팝업 -->\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/view/system/comncod.jsp(4,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userType ne 'A'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    ");
          if (_jspx_meth_c_005fredirect_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fredirect_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:redirect
    org.apache.taglibs.standard.tag.rt.core.RedirectTag _jspx_th_c_005fredirect_005f0 = (org.apache.taglibs.standard.tag.rt.core.RedirectTag) _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.RedirectTag.class);
    boolean _jspx_th_c_005fredirect_005f0_reused = false;
    try {
      _jspx_th_c_005fredirect_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fredirect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/view/system/comncod.jsp(5,4) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fredirect_005f0.setUrl("/dashboard/dashboard.do");
      int _jspx_eval_c_005fredirect_005f0 = _jspx_th_c_005fredirect_005f0.doStartTag();
      if (_jspx_th_c_005fredirect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fredirect_0026_005furl_005fnobody.reuse(_jspx_th_c_005fredirect_005f0);
      _jspx_th_c_005fredirect_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fredirect_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fredirect_005f0_reused);
    }
    return false;
  }
}
