/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2024-07-22 00:35:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.management;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>제품 정보 관리</title>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/common_include.jsp", out, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<input type=\"hidden\" id=\"currentPage\" value=\"\">  <!-- 현재페이지는 처음에 항상 1로 설정하여 넘김  -->\r\n");
      out.write("\t<input type=\"hidden\" name=\"action\" id=\"action\" value=\"\"> \r\n");
      out.write("\t<div id=\"wrap_area\">\r\n");
      out.write("\t\t<h2 class=\"hidden\">header 영역</h2> \r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<h2 class=\"hidden\">컨텐츠 영역</h2>\r\n");
      out.write("\t\t<div id=\"container\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"lnb\">\r\n");
      out.write("\t\t\t\t\t<!-- lnb 영역 --> \r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/lnbMenu.jsp", out, false);
      out.write(" <!--// lnb 영역 -->\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"contents\">\r\n");
      out.write("\t\t\t\t\t<!-- contents -->\r\n");
      out.write("\t\t\t\t\t<h3 class=\"hidden\">contents 영역</h3> <!-- content -->\r\n");
      out.write("\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<p class=\"conTitle\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<select id=\"searchCondition\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0\">제품명</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">제품코드명</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">제조사</option>\r\n");
      out.write("\t\t\t\t\t\t</select> \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<span class=\"fr\">\t\t\t\t\t\r\n");
      out.write("                          <input type=\"text\" id=\"searchTitle\" name=\"searchTitle\" style=\"height: 25px; margin-right: 10px;\"/>\r\n");
      out.write("                          \r\n");
      out.write("                          <a class=\"btnType red\" name=\"searchbtn\"  id=\"searchBtn\"><span>검색</span></a>\r\n");
      out.write("                          \r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</p> \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"divNoticeList\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\t\t                            <colgroup>\r\n");
      out.write("\t\t\t\t\t\t                    <col width=\"60px\">\r\n");
      out.write("\t\t\t\t\t\t                   <col width=\"80px\">\r\n");
      out.write("\t\t\t\t\t\t                   <col width=\"70px\">\r\n");
      out.write("\t\t\t\t\t\t                   <col width=\"50px\">\r\n");
      out.write("\t\t\t\t\t                 </colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t              \r\n");
      out.write("\t\t\t\t\t\t\t              <th scope=\"col\">제품 코드</th>\r\n");
      out.write("\t\t\t\t\t\t\t              <th scope=\"col\">제품 명</th>\r\n");
      out.write("\t\t\t\t\t\t\t              <th scope=\"col\">제조사</th>\r\n");
      out.write("\t\t\t\t\t\t\t              <th scope=\"col\">판매가</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody id=\"productList\"></tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 페이징 처리  -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"paging_area\" id=\"pagingNavi\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"btnType red\" name=\"newRegister\"  id=\"newRegister\"><span>제품 등록</span></a>\r\n");
      out.write("\t\t\t\t\t</div> <!--// content -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"myModal\" class=\"modal\" style=\"width: max;\" >\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"120px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"*\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"120px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"*\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"close\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr id=\"imageTag\">\r\n");
      out.write("            \t\t\t\t\t\t\t<th>이미지</th>\r\n");
      out.write("            \t\t\t\t\t\t\t<td colspan=\"3\"><img id=\"productImg\" src=\"\" alt=\"제품 이미지\" style=\"width:100%;max-width:300px\"></td>\r\n");
      out.write("            \t\t\t\t\t\t</tr>\r\n");
      out.write("            \t\t\t\t\t\t<tr>\r\n");
      out.write("            \t\t\t\t\t\t\t<th scope=\"row\">제품 번호</th> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td ><input type=\"text\" id=\"modalProductCode\" style=\"height: 25px; margin-right: 10px;\" class=\"inputTxt p100\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"row\">제품 명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td ><input type=\"text\" id=\"modalProductName\" style=\"height: 25px; margin-right: 10px;\" class=\"inputTxt p100\"/><br></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"row\">제조사</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td ><input type=\"text\" id=\"modalManufac\" style=\"height: 25px; margin-right: 10px;\" class=\"inputTxt p100\"/><br></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"row\">제품 가격</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td ><input type=\"text\" id=\"modalValue\" style=\"height: 25px; margin-right: 50px;\" class=\"inputTxt p100\"/><br></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"row\" >상세 정보</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"5\"><textarea id=\"modaldetail\" style=\"height: 25px; margin-right: 50px;\" class=\"inputTxt p100\" colspan=\"2\" cols=\"40\" rows=\"5\"></textarea><br></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("            \t\t\t\t</table>\t\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"modalProductCodeOrigin\" >\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"modalProductNameOrigin\" >\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" id=\"modalManufacOrigin\" >\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn2 btn-primary\">저장</button>\r\n");
      out.write("                \t\t\t\t<button class=\"btn1 btn-primary\">삭제</button>\r\n");
      out.write("                \t\t\t\t<button class=\"btn btn-primary\">취소</button>\t\t\t\t\t\t\r\n");
      out.write("            \t\t\t\t</div>\r\n");
      out.write("            \t\t\t\t\r\n");
      out.write("            \t\t\t\r\n");
      out.write("        \t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<h3 class=\"hidden\">풋터 영역</h3>\r\n");
      out.write("\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var pageSize = 5;\r\n");
      out.write("var pageBlockPage = 10;\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    \r\n");
      out.write("    $(\"#newRegister\").click(function() {\r\n");
      out.write("    \t$(\".btn1\").hide();\r\n");
      out.write("    \t$(\"#myModal\").show();\r\n");
      out.write("    \t$('#modalProductCode').val('');\r\n");
      out.write("    \t$('#modalProductName').val('');\r\n");
      out.write("    \t$('#modalManufac').val('');\r\n");
      out.write("    \t$('#modalValue').val('');\r\n");
      out.write("    \t$('#modaldetail').val('');\r\n");
      out.write("    \tdocument.getElementById('productImg').src = '';\r\n");
      out.write("    \t$(\"#imageTag\").hide();\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    $(\"#searchBtn\").click(function() {  //검색 버튼 클릭 이벤트\r\n");
      out.write("    \tdetailSearch();\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    $(\".close\").click(function() {\r\n");
      out.write("    \t$(\"#myModal\").hide();\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    $(\".btn\").click(function() {\r\n");
      out.write("    \t$(\"#myModal\").hide();\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    $(\".btn1\").click(function() { //삭제 버튼\r\n");
      out.write("    \tvar itemCode = $(\"#modalProductCode\").val();\r\n");
      out.write("    \tproductDelete(itemCode);\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    $(\".btn2\").click(function() { // 저장버튼\r\n");
      out.write("    \tproductRegist();\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("     \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\tgetProductList();\r\n");
      out.write("\t//var newSrc=\"/test.jsp\";\r\n");
      out.write("\t//document.getElementById('productImg').src = newSrc;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getProductList(cpage){\r\n");
      out.write("\tcpage = cpage || 1;\r\n");
      out.write("\t\r\n");
      out.write("\t// 공지사항 데이터 보여주는 로직\r\n");
      out.write("\tvar param = {\r\n");
      out.write("\t\t\tcurrentPage : cpage,\r\n");
      out.write("\t\t\tpageSize : pageSize\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tvar callBackFunction = function(response){\r\n");
      out.write("\t\t$(\"#productList\").empty().append(response);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar pagieNavigateHtml = getPaginationHtml(cpage, $(\"#totcnt\").val(), pageSize, pageBlockPage, \"getProductList\")\r\n");
      out.write("\t\t$(\"#pagingNavi\").empty().append(pagieNavigateHtml);\r\n");
      out.write("\t\t$(\"#currentPage\").val(cpage);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tcallAjax(\"/management/getProductList.do\", \"post\", \"text\", false, param,callBackFunction);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function detailSearch(cpage){ /////검색 기능\r\n");
      out.write("\tcpage = cpage || 1;\r\n");
      out.write("\tvar searchTitle = $('#searchTitle').val();\r\n");
      out.write("\tvar condition = $('#searchCondition').val();\r\n");
      out.write("\tvar itemCode = \"\";\r\n");
      out.write("\tvar itemName = \"\";\r\n");
      out.write("\tvar manufac = \"\";\r\n");
      out.write("\t\r\n");
      out.write("\tswitch(condition){\r\n");
      out.write("\tcase \"0\":\r\n");
      out.write("\t\titemName = searchTitle;\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\tcase \"1\":\r\n");
      out.write("\t\titemCode = searchTitle;\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\tcase \"2\":\r\n");
      out.write("\t\tmanufac = searchTitle;\r\n");
      out.write("\t\tbreak;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar param = {\r\n");
      out.write("\t\t\tsearchItemName : itemName,\r\n");
      out.write("\t\t\tsearchItemCode : itemCode,\r\n");
      out.write("\t\t\tsearchManufac : manufac,\r\n");
      out.write("\t\t\tcondition : condition,\r\n");
      out.write("\t\t\tcurrentPage : cpage,\r\n");
      out.write("\t\t\tpageSize : pageSize\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tvar callBackFunction = function(response){\r\n");
      out.write("\t\t$(\"#productList\").empty().append(response);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar pagieNavigateHtml = getPaginationHtml(cpage, $(\"#totcnt\").val(), pageSize, pageBlockPage, \"detailSearch\")\r\n");
      out.write("\t\t$(\"#pagingNavi\").empty().append(pagieNavigateHtml);\r\n");
      out.write("\t\t$(\"#currentPage\").val(cpage);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tcallAjax(\"/management/productSearch.do\", \"post\", \"text\", false, param,callBackFunction);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function productRegist(){ // 저장 버튼 클릭 시 발동\r\n");
      out.write("\tvar product_code = $('#modalProductCode').val();\r\n");
      out.write("\tvar product_name= $('#modalProductName').val();\r\n");
      out.write("\tvar manufac= $('#modalManufac').val();\r\n");
      out.write("\tvar product_value= $('#modalValue').val();\r\n");
      out.write("\tvar product_detail= $('#modaldetail').val();\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar param = {\r\n");
      out.write("\t\t\tproduct_code : product_code,\r\n");
      out.write("\t\t\tproduct_name : product_name,\r\n");
      out.write("\t\t\tmanufac : manufac,\r\n");
      out.write("\t\t\tproduct_value : product_value,\r\n");
      out.write("\t\t\tproduct_detail : product_detail\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar callBackFunction = function(response){\r\n");
      out.write("\t\talert(\"등록 됐습니다\");\r\n");
      out.write("\t\t$(\"#myModal\").hide();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tcallAjax(\"/management/productRegist.do\", \"post\", \"text\", false, param,callBackFunction);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function productDelete(itemCode){ // 삭제 버튼 클릭 시 발동\r\n");
      out.write("\t\r\n");
      out.write("\tvar param = {\r\n");
      out.write("\t\t\tproduct_code : itemCode\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("\tvar callBackFunction = function(response){\r\n");
      out.write("\t\talert(\"삭제 됐습니다\");\r\n");
      out.write("\t\t$(\"#myModal\").hide();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tcallAjax(\"/management/productDelete.do\", \"post\", \"text\", false, param,callBackFunction);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("        /* 모달 배경 */\r\n");
      out.write("        .modal {\r\n");
      out.write("            display: none; /* 기본적으로 모달을 숨김 */\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            overflow: hiddent;\r\n");
      out.write("            background-color: rgb(0,0,0);\r\n");
      out.write("            background-color: rgba(0,0,0,0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 모달 콘텐츠 */\r\n");
      out.write("        .modal-content {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            left: 58%;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            transform: translate(-50%, -50%);\r\n");
      out.write("            background-color: #fefefe;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            border: 1px solid #888;\r\n");
      out.write("            width: 80%;\r\n");
      out.write("            max-width: 600px; /* 최대 너비 설정 */\r\n");
      out.write("            box-shadow: 0px 5px 15px rgba(0,0,0,0.5);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 닫기 버튼 */\r\n");
      out.write("        .close {\r\n");
      out.write("            color: #aaa;\r\n");
      out.write("            float: right;\r\n");
      out.write("            font-size: 28px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .close:hover,\r\n");
      out.write("        .close:focus {\r\n");
      out.write("            color: black;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("         /* 모달 안의 버튼 */\r\n");
      out.write("        .modal-footer .btn {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: 20px;\r\n");
      out.write("            right: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .modal-footer .btn2 {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: 20px;\r\n");
      out.write("            right: 60px;\r\n");
      out.write("        }\r\n");
      out.write("        .modal-footer .btn1 {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            bottom: 20px;\r\n");
      out.write("            right: 100px;\r\n");
      out.write("        }\r\n");
      out.write("</style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
