/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2024-06-24 00:52:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.personal;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class personalInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1717304976992L));
    _jspx_dependants.put("jar:file:/C:/Users/user/git/egov/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/marlmsone1/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<title>마이페이지 : 정보 수정</title>\r\n");
      out.write("<!-- 우편코드 -->\r\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" charset=\"utf-8\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CTX_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/popFindZipCode.js\"></script>\r\n");
      out.write("<!-- sweet alert import -->\r\n");
      out.write("<script src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CTX_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/sweetalert/sweetalert.min.js'></script>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/common_include.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- sweet swal import -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\tdiv #necessary th{\ttext-align: center;\tfont-weight: bold; background-color: #d3d3d3; }\r\n");
      out.write("\tdiv #necessary td {background-color: #FFFFFF;}\r\n");
      out.write("\tdiv #necessary .btn {background-color: #d3d3d3;}\r\n");
      out.write("\tdiv #necessary td input{\tborder: none; height: 35px; width:100%;}\r\n");
      out.write("\tdiv #additionalPart th {\ttext-align: center;\tfont-weight: bold; background-color: #d3d3d3; }\r\n");
      out.write("\tdiv #additionalPart td {\ttext-align: left; border:none;}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\t\r\n");
      out.write("\r\n");
      out.write("\t/** OnLoad event */ \r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tfRegisterButtonClickEvent();\r\n");
      out.write("\t\t// 학생일 경우에만 추가입력사항 확인\r\n");
      out.write("\t\tif($(\"#userType\").val()== \"A\"){\r\n");
      out.write("\t\t\t$(\"#additionalPart\").show();\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$(\"#additionalPart\").hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t// 필터링\r\n");
      out.write("\t/*패스워드 정규식*/\r\n");
      out.write("\tfunction formatPassword() {\r\n");
      out.write("\t\tvar passwordRules = /^.*(?=^.{8,15}$)(?=.*\\d)(?=.*[a-zA-Z])(?=.*[!@#$%^&+=]).*$/;\r\n");
      out.write("\t \tvar password = $(\"#newPsd\").val();\r\n");
      out.write("\t\tif(!passwordRules.test($(\"#newPsd\").val())){\r\n");
      out.write("\t\t\tswal('비밀 번호는 숫자,영문자,특수문자 조합으로 8~15자리를 사용해야 합니다.').then(function() {\r\n");
      out.write("\t\t\t\t$(\"#registerPwd\").focus();\r\n");
      out.write("\t\t  });\r\n");
      out.write("\t\t}else {\r\n");
      out.write("\t\t\tchangePwd();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/** 휴대폰 번호 필터링 */\r\n");
      out.write("    function formatPhoneNumber() {\r\n");
      out.write("        var searchWord_std = document.getElementById(\"tel\");\r\n");
      out.write("        \r\n");
      out.write("        // 숫자로만 이루어진 문자열인지 확인\r\n");
      out.write("        var phoneNumber = searchWord_std.value.replace(/[^0-9]/g, \"\");\r\n");
      out.write("\r\n");
      out.write("        // 처음 3자리가 허용된 번호인지 확인\r\n");
      out.write("        if (phoneNumber.length==3){\r\n");
      out.write("        var prefix = phoneNumber.substring(0, 3);\r\n");
      out.write("    \t    if ([\"010\", \"019\", \"011\", \"016\", \"017\"].indexOf(prefix) === -1) {\r\n");
      out.write("    \t    \talert(\"정확한 전화번호를 입력해주세요.\");\r\n");
      out.write("    \t    \t$(\"#tel\").val(\"\").focus();\r\n");
      out.write("    \t        return;  // 허용되지 않은 번호이면 함수를 종료\r\n");
      out.write("    \t    }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // 휴대폰 번호 형식에 맞게 하이픈 추가\r\n");
      out.write("        if (phoneNumber.length >= 3 && phoneNumber.length <= 7) {\r\n");
      out.write("          phoneNumber = phoneNumber.replace(/(\\d{3})(\\d{1,4})/, \"$1-$2\");\r\n");
      out.write("        } else if (phoneNumber.length >= 8) {\r\n");
      out.write("          phoneNumber = phoneNumber.replace(/(\\d{3})(\\d{3,4})(\\d{0,4})/, \"$1-$2-$3\");\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // 13자리까지만 입력받기 (한국기준)\r\n");
      out.write("        if (phoneNumber.length > 13) {\r\n");
      out.write("            phoneNumber = phoneNumber.substring(0, 13);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // 입력된 내용을 변경된 번호로 업데이트\r\n");
      out.write("        searchWord_std.value = phoneNumber;\r\n");
      out.write("    }\r\n");
      out.write("\t\r\n");
      out.write("\t/** 이메일 필터링 */\r\n");
      out.write("\tfunction validateEmail() {\r\n");
      out.write("       var emailInput = $(\"#mail\").val();\r\n");
      out.write("       var regex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$/;\r\n");
      out.write("\r\n");
      out.write("       if (!regex.test(emailInput)) {\r\n");
      out.write("    \t   alert(\"올바른 형식의 이메일을 입력하세요.\");\r\n");
      out.write("\t\t\t$(\"#mail\").val().focus();\r\n");
      out.write("       } \r\n");
      out.write("    }\r\n");
      out.write("\t\r\n");
      out.write("\t/** 버튼 이벤트 등록 */\r\n");
      out.write("\tfunction fRegisterButtonClickEvent() {\r\n");
      out.write("\t\t// input 이름이 btn 인 경우\r\n");
      out.write("\t\t$('input[name=btn]').click(function(e) {\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 현재 입력된 객체의 id 를 가져옴\r\n");
      out.write("\t\t\tvar btnId = $(this).attr('id');\r\n");
      out.write("          \r\n");
      out.write("\t\t\t// id 값으로 행동을 분기\r\n");
      out.write("\t\t\tswitch (btnId) {\r\n");
      out.write("\t\t\t\tcase 'savebtn' :\r\n");
      out.write("\t\t\t\t\tSave();\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase 'changePwd' :\r\n");
      out.write("\t\t\t\t\tPwd();\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase 'changeZipcode' :\r\n");
      out.write("\t\t\t\t\taddr();\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase 'btnClose' :\r\n");
      out.write("\t\t\t\t\tgfCloseModal();\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t/** 필수 정보 입력 validation */\r\n");
      out.write("\tfunction fValidate() {\r\n");
      out.write("\t\tvar chk = checkNotEmpty(\r\n");
      out.write("\t\t\t\t[\r\n");
      out.write("\t\t\t\t\t\t[ \"pwdCheck\", \"사용중인 비밀번호를 입력해주세요\" ]\r\n");
      out.write("\t\t\t\t\t,\t[ \"tel\", \"연락처를 입력하세요\" ]\r\n");
      out.write("\t\t\t\t]\r\n");
      out.write("\t\t);\r\n");
      out.write("\r\n");
      out.write("\t\tif (!chk) {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 정보 validation 확인 및 저장하는 함수\r\n");
      out.write("\tfunction Save(){\r\n");
      out.write("\t\t// flase 값이 들어오면 -> return\r\n");
      out.write("\t\tif(!fValidate()){\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 이메일 확인\r\n");
      out.write("\t\tvalidateEmail();\r\n");
      out.write("\r\n");
      out.write("\t\t// 입력한 비밀번호와 일치하는지 확인\r\n");
      out.write("\t\tmyPwdCheck()\r\n");
      out.write("\t\tupload();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t// 파일 업로드\r\n");
      out.write("\tfunction upload(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 파일처리 시작\r\n");
      out.write("\t\tvar frm = document.getElementById(\"myForm\");\r\n");
      out.write("\t\tfrm.enctype = 'multipart/form-data';\r\n");
      out.write("\t\tvar fileData = new FormData(frm);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar callback = function(response){\r\n");
      out.write("\t\t\talert(response.resultmsg);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(response.result===\"S\"){\r\n");
      out.write("\t\t\t\t// 새로고침하기\r\n");
      out.write("\t\t\t\tlocation.href = location.href;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcallAjaxFileUploadSetFormData(\"/personal/personalSave.do\", \"post\", \"json\", false, fileData, callback);\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 파일 다운로드\r\n");
      out.write("\tfunction download(){\r\n");
      out.write("\t\t$(\"<form action='personalDownload.do' method='post' id='fileDownload'></form>\"\r\n");
      out.write("\t\t).appendTo('body').submit().remove();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 비밀번호 변경창 띄우는 메소드\r\n");
      out.write("\tfunction Pwd(){\r\n");
      out.write("\t\tgfModalPop(\"#layer1\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 비밀번호 변경창 체크 및 저장\r\n");
      out.write("\tfunction changePwd(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar newPsd = $(\"#newPsd\").val();\r\n");
      out.write("\t\tvar newPsdCheck = $(\"#newPsdCheck\").val();\r\n");
      out.write("\t\tvar originPwd = $(\"#originPwd\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 값을 입력하지 않았을 때 check\r\n");
      out.write("\t\tif(newPsd===null || isEmpty(newPsd))\r\n");
      out.write("\t\t\treturn $(\"#newPsd\").focus();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(newPsd===null || isEmpty(newPsd))\r\n");
      out.write("\t\t\treturn $(\"#originPwd\").focus();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(newPsd===null || isEmpty(newPsd))\r\n");
      out.write("\t\t\treturn $(\"#originPwd\").focus();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 값 validation\r\n");
      out.write("\t\tif(newPsd !== newPsdCheck){\r\n");
      out.write("\t\t\talert(\"새로운 비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("\t\t\t$(\"#newPsdCheck\").focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// AJAX 로 변경\r\n");
      out.write("\t\tvar param = {\r\n");
      out.write("\t\t\t\tnewPsd : $(\"#newPsd\").val(),        \r\n");
      out.write("\t\t\t\toriginPwd : $(\"#originPwd\").val(),\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar callback = function(response){\r\n");
      out.write("\t\t\tvar message = response.resultmsg;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(message===\"FAIL1\"){\r\n");
      out.write("\t\t\t\talert(\"비밀번호 변경에 실패하였습니다.\\n지속적인 문제 발생 시 관리자에게 문의바랍니다.\");\r\n");
      out.write("\t\t\t\treturn gfCloseModal();\r\n");
      out.write("\t\t\t} else if(message===\"FAIL2\") {\r\n");
      out.write("\t\t\t\talert(\"이전에 비밀번호와 동일하게 설정할 수 없습니다.\");\r\n");
      out.write("\t\t\t\treturn $(\"#newPsd\").focus();\r\n");
      out.write("\t\t\t} else if(message===\"FAIL3\") {\r\n");
      out.write("\t\t\t\talert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("\t\t\t\treturn $(\"#originPwd\").focus();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\talert(\"비밀번호가 변경되었습니다.\");\r\n");
      out.write("\t\t\treturn gfCloseModal();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcallAjax(\"/personal/personalPwdChange.do\", \"post\", \"json\", false, param, callback);\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction Quit(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar data = $(\"#pwdCheck\").val();\r\n");
      out.write("\t\tif(data===null || data===\"\"){\r\n");
      out.write("\t\t\talert(\"비밀번호를 입력해주세요!\");\r\n");
      out.write("\t\t\treturn $(\"#pwdCheck\").focus();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tmyPwdCheck().then(function(isMatch) {\r\n");
      out.write("\t        if(!isMatch){\r\n");
      out.write("\t            alert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("\t            $(\"#pwdCheck\").focus();\r\n");
      out.write("\t            return;\r\n");
      out.write("\t        }\r\n");
      out.write("\r\n");
      out.write("\t        if(confirm(\"정말 탈퇴하시겠습니까?\\n되돌릴 수 없습니다.\")){\r\n");
      out.write("\t            var callback = function(response){\r\n");
      out.write("\t                if(response.resultmsg===\"SUCCESS\"){\r\n");
      out.write("\t                    alert(\"성공적으로 탈퇴하였습니다.\");\r\n");
      out.write("\t                    gfCloseModal();\r\n");
      out.write("\t                    fLogOut();\r\n");
      out.write("\t                } else {\r\n");
      out.write("\t                    alert(\"탈퇴 실패하였습니다.\\n문제가 계속 발생되면 관리자에게 문의바랍니다.\");\r\n");
      out.write("\t                }\r\n");
      out.write("\t            }\r\n");
      out.write("\r\n");
      out.write("\t            callAjax(\"/personal/personalQuit.do\", \"post\", \"json\", false, \"\", callback);\t\r\n");
      out.write("\t        }\r\n");
      out.write("\t    });\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction addr (){\r\n");
      out.write("\t\tpopFindZipCode();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction myPwdCheck(){\r\n");
      out.write("\t    return new Promise(function(resolve, reject) {\r\n");
      out.write("\t        var param = {\r\n");
      out.write("\t            password : $(\"#pwdCheck\").val()\r\n");
      out.write("\t        }\r\n");
      out.write("\r\n");
      out.write("\t        var callback = function(response){\r\n");
      out.write("\t            if(response.resultmsg===\"SUCCESS\"){\r\n");
      out.write("\t                console.log(\"비번 일치 조회 성공\");\r\n");
      out.write("\t                resolve(true);\r\n");
      out.write("\t            } else {\r\n");
      out.write("\t                resolve(false);\r\n");
      out.write("\t            }\r\n");
      out.write("\t        }\r\n");
      out.write("\t        callAjax(\"/personal/checkPwd.do\", \"post\", \"json\", false, param, callback);\t\r\n");
      out.write("\t    });\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form id=\"myForm\" action=\"\"  method=\"\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"userType\" name=\"userType\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 모달 배경 -->\r\n");
      out.write("\t<div id=\"mask\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"wrap_area\">\r\n");
      out.write("\r\n");
      out.write("\t\t<h2 class=\"hidden\">header 영역</h2>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<h2 class=\"hidden\">컨텐츠 영역</h2>\r\n");
      out.write("\t\t<div id=\"container\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"lnb\">\r\n");
      out.write("\t\t\t\t\t<!-- lnb 영역 --> ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/lnbMenu.jsp", out, false);
      out.write(" <!--// lnb (메뉴) 영역 -->\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"contents\">\r\n");
      out.write("\t\t\t\t\t<!-- contents -->\r\n");
      out.write("\t\t\t\t\t<h3 class=\"hidden\">contents 영역</h3> <!-- content -->\r\n");
      out.write("\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p class=\"Location\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"../notice/aNotice.do\" class=\"btn_set home\">메인으로</a> <span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"btn_nav bold\">MY PAGE</span> <span class=\"btn_nav bold\"> 정보 수정\r\n");
      out.write("\t\t\t\t\t\t\t\t</span> <a href=\"../system/comnCodMgr.do\" class=\"btn_set refresh\">새로고침</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p class=\"conTitle\">\r\n");
      out.write("\t\t                     <span>필수 입력사항 </span>\r\n");
      out.write("                  \t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"divComGrpCodList\" id=\"necessary\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"30%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"30%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">아이디</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td scope=\"col\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"loginId\" name=\"loginId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" readonly=\"readonly\" class=\"readonly\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">이름</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td scope=\"col\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"name\" name=\"name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" readonly=\"readonly\" class=\"readonly\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">비밀번호 확인<span class=\"font_red\"> *</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td scope=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" id=\"pwdCheck\" name=\"pwdCheck\" value=\"\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td scope=\"col\" class=\"btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"button\" id=\"changePwd\" name=\"btn\" class=\"form-control btn\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"비밀번호 변경\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">우편번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td scope=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"zipcode\" name=\"zipcode\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.zipcode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\treadonly=\"readonly\" class=\"readonly\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td scope=\"col\" class=\"btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"button\" id=\"changeZipcode\" class=\"form-control btn\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"btn\" value=\"우편번호 찾기\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\" >이메일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td scope=\"col\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"mail\" name=\"mail\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.mail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">주소</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td scope=\"col\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"addr\" name=\"addr\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.addr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" readonly=\"readonly\" class=\"readonly\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">연락처<span class=\"font_red\"> *</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td scope=\"col\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"tel\" name=\"tel\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.tel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" oninput=\"javascript:formatPhoneNumber()\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"숫자만 입력\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">상세주소</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td scope=\"col\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"addr_dtl\" name=\"addr_dtl\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.addr_dtl}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"동, 층, 호수를 입력해주세요\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div id=\"additionalPart\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"conTitle\" style=\"margin-top: 50px;\">\r\n");
      out.write("\t\t\t                     <span>추가 입력사항 </span>\r\n");
      out.write("\t                  \t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"divComGrpCodList\" id=\"additional\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"90%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">이력서(다운로드)</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td scope=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"file\" id=\"resume\" name=\"resume\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.resume_fname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:download()\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.resume_fname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div style=\"text-align: center; margin-top: 50px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btnType blue\" href=\"javascript:Save();\" id=\"savebtn\" name=\"btn\"><span>저장</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"btnType grey\" href=\"javascript:Quit();\"><span>탈퇴하기</span></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t</div> <!--// content -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<h3 class=\"hidden\">풋터 영역</h3>\r\n");
      out.write("\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 모달팝업 // 비밀번호 변경  -->\r\n");
      out.write("\t<div id=\"layer1\" class=\"layerPop layerType2\" style=\"width: 600px;\">\r\n");
      out.write("\t\t<dl>\r\n");
      out.write("\t\t\t<dt>\r\n");
      out.write("\t\t\t\t<strong>비밀번호 변경</strong>\r\n");
      out.write("\t\t\t</dt>\r\n");
      out.write("\t\t\t<dd class=\"content\">\r\n");
      out.write("\t\t\t\t<!-- s : 여기에 내용입력 -->\r\n");
      out.write("\t\t\t\t<table class=\"row\">\r\n");
      out.write("\t\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col width=\"150px\">\r\n");
      out.write("\t\t\t\t\t\t<col width=\"*\">\r\n");
      out.write("\t\t\t\t\t\t<col width=\"150px\">\r\n");
      out.write("\t\t\t\t\t\t<col width=\"*\">\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th colspan=\"4\" style=\"text-align: center; background-color:#f9f9f9; color: red; height:80px ; font-size: 10pt;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t*이전에 사용한 적 없는 비밀번호가 안전합니다.<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t새로운 비밀번호로 변경해주세요.\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>새로운 비밀번호<span class=\"font_red\"> *</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" id=\"newPsd\"  name=\"newPsd\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border: none; height: 35px; width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>새로운 비밀번호 확인<span class=\"font_red\"> *</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" id=\"newPsdCheck\"  name=\"newPsdCheck\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border: none; height: 35px; width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>현재 비밀번호 확인<span class=\"font_red\"> *</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" id=\"originPwd\"  name=\"originPwd\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"border: none; height: 35px; width:100%;\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- e : 여기에 내용입력 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"btn_areaC mt30\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:formatPassword();\" class=\"btnType blue\" id=\"btnChangeSave\" name=\"btn\"><span>저장</span></a> \r\n");
      out.write("\t\t\t\t\t<a href=\"\"\tclass=\"btnType gray\"  id=\"btnClose\" name=\"btn\"><span>취소</span></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t\t<a href=\"\" class=\"closePop\"><span class=\"hidden\">닫기</span></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!--// 모달팝업 -->\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
