/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2024-06-18 11:13:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.employ;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class employ_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/user/git/egov/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/marlmsone1/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1717304976992L));
    _jspx_dependants.put("jar:file:/C:/Users/user/git/egov/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/marlmsone1/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      java.util.Date now = null;
      now = (java.util.Date) _jspx_page_context.getAttribute("now", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (now == null){
        now = new java.util.Date();
        _jspx_page_context.setAttribute("now", now, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<title>취업 정보</title>\r\n");
      out.write("<!-- sweet alert import -->\r\n");
      out.write("\r\n");
      out.write("<script src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${CTX_PATH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/sweetalert/sweetalert.min.js'></script>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/common_include.jsp", out, false);
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar pageSize = 5; // -- 한 페이지 당 몇개 보여줄 지\r\n");
      out.write("\tvar pageBlocksize = 5; // -- 페이지 당 번호\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function(e) {\r\n");
      out.write("\t\tconsole.log('employ')\r\n");
      out.write("\t\tfRegisterButtonClickEvent();\r\n");
      out.write("\t\tfRegisterButtonClickEvent2();\r\n");
      out.write("\t\tfListEmp(); // 취업 목록 리스트\r\n");
      out.write("\t\tstdSearch();\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\tfunction fRegisterButtonClickEvent() {\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#searchEnter\").click(function(e) {\r\n");
      out.write("\t\t\t// ?\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\r\n");
      out.write("\t\t\tfListEmp();\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t// a 태그의 이름이 btn 인 경우\r\n");
      out.write("\t\t$('a[name=btn]').click(function(e) {\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 현재 입력된 객체의 id 를 가져옴\r\n");
      out.write("\t\t\tvar btnId = $(this).attr('id');\r\n");
      out.write("\r\n");
      out.write("\t\t\t// id 값으로 행동을 분기\r\n");
      out.write("\t\t\tswitch (btnId) {\r\n");
      out.write("\t\t\tcase 'btnSave':\r\n");
      out.write("\t\t\t\tSave();\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\tcase 'btnDelete':\r\n");
      out.write("\t\t\t\tdeletelec();\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\tcase 'btnSaveEqu':\r\n");
      out.write("\t\t\t\tSaveEqu();\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\tcase 'btnDeleteEqu':\r\n");
      out.write("\t\t\t\tDeleteEqu();\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\tcase 'btnClose':\r\n");
      out.write("\t\t\t\tgfCloseModal();\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction fRegisterButtonClickEvent2() {\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#searchEnter1\").click(function(e) {\r\n");
      out.write("\t\t\t// ?\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\r\n");
      out.write("\t\t\tstdSearch();\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t// a 태그의 이름이 btn 인 경우\r\n");
      out.write("\t\t$('a[name=btn]').click(function(e) {\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 현재 입력된 객체의 id 를 가져옴\r\n");
      out.write("\t\t\tvar btnId = $(this).attr('id');\r\n");
      out.write("\r\n");
      out.write("\t\t\t// id 값으로 행동을 분기\r\n");
      out.write("\t\t\tswitch (btnId) {\r\n");
      out.write("\t\t\tcase 'btnSave':\r\n");
      out.write("\t\t\t\tSave();\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\tcase 'btn_employ':\r\n");
      out.write("\t\t\t\tbtn_employ();\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\tcase 'btnSaveEqu':\r\n");
      out.write("\t\t\t\tSaveEqu();\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\tcase 'btnDeleteEqu':\r\n");
      out.write("\t\t\t\tDeleteEqu();\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\tcase 'btnClose':\r\n");
      out.write("\t\t\t\tgfCloseModal();\r\n");
      out.write("\t\t\t\tbreak;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/* 취업 목록 조회 */\r\n");
      out.write("\tfunction fListEmp(currentPage) {\r\n");
      out.write("\r\n");
      out.write("\t\tcurrentPage = currentPage || 1;\r\n");
      out.write("\r\n");
      out.write("\t\tconsole.log(\"currentPage : \" + currentPage + \" searchKey : \", searchKey\r\n");
      out.write("\t\t\t\t+ \" searchInfo : \", searchInfo);\r\n");
      out.write("\r\n");
      out.write("\t\tvar param = {\r\n");
      out.write("\t\t\tpageSize : pageSize,\r\n");
      out.write("\t\t\tcurrentPage : currentPage,\r\n");
      out.write("\t\t\tsearchInfo : $(\"#searchInfo\").val(),\r\n");
      out.write("\t\t\tsearchKey : $(\"#searchKey\").val()\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tconsole.log(\"param : \", param);\r\n");
      out.write("\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '/employ/listEmp.do',\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdata : param,\r\n");
      out.write("\t\t\tasync : true,\r\n");
      out.write("\t\t\tdataType : \"text\",\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\tgetListEmp(data, currentPage);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(error) {\r\n");
      out.write("\t\t\t\tconsole.log(error)\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction getListEmp(data, currentPage) {\r\n");
      out.write("\t\tconsole.log(\"data : \", data);\r\n");
      out.write("\t\t$(\"#listEmp\").empty().append(data);\r\n");
      out.write("\t\tvar totCnt = $(\"#emp_Total\").val();\r\n");
      out.write("\t\tconsole.log(\"totCnt : \" + totCnt);\r\n");
      out.write("\r\n");
      out.write("\t\tvar paginationHtml = getPaginationHtml(currentPage, totCnt, pageSize,\r\n");
      out.write("\t\t\t\tpageBlocksize, 'fListEmp');\r\n");
      out.write("\r\n");
      out.write("\t\tconsole.log(currentPage);\r\n");
      out.write("\t\tconsole.log(totCnt);\r\n");
      out.write("\t\tconsole.log(pageSize);\r\n");
      out.write("\t\tconsole.log(pageBlocksize);\r\n");
      out.write("\r\n");
      out.write("\t\tconsole.log(\"paginationHtml : \" + paginationHtml);\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#Pagination\").empty().append(paginationHtml);\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#currentPage\").val(currentPage);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/* 강의 별 학생 리스트(아이디) */\r\n");
      out.write("\tfunction stdList(std_id) {\r\n");
      out.write("\t\t$(\"#std_id\").val(std_id);\r\n");
      out.write("\t\tstdSearch();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/* 강의 별 학생 리스트(페이지)*/\r\n");
      out.write("\tfunction stdSearch(currentPage) {\r\n");
      out.write("\r\n");
      out.write("\t\tcurrentPage = currentPage || 1;\r\n");
      out.write("\r\n");
      out.write("\t\tconsole.log(\"stdSearch탐 : \" + currentPage);\r\n");
      out.write("\r\n");
      out.write("\t\tvar param = {\r\n");
      out.write("\t\t\tloginID : $(\"#std_id\").val(),\r\n");
      out.write("\t\t\tcurrentPage : currentPage,\r\n");
      out.write("\t\t\tpageSize : pageSize,\r\n");
      out.write("\t\t\tsearchInfo1 : $(\"#searchInfo1\").val(),\r\n");
      out.write("\t\t\tsearchKey1 : $(\"#searchKey1\").val()\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tconsole.log(\"학생param : \", param);\r\n");
      out.write("\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '/employ/empstdList.do',\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdata : param,\r\n");
      out.write("\t\t\tasync : true,\r\n");
      out.write("\t\t\tdataType : \"text\",\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\tgetStdList(data, currentPage);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(error) {\r\n");
      out.write("\t\t\t\tconsole.log(error)\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction getStdList(data, currentPage) {\r\n");
      out.write("\t\tconsole.log(\"학생data: \", data);\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#div_std_list\").show();\r\n");
      out.write("\t\t$(\"#EmpStdPagination\").show();\r\n");
      out.write("\t\t$(\"#listEmpStd\").empty().append(data);\r\n");
      out.write("\r\n");
      out.write("\t\tvar totCnt = $(\"#std_Total\").val();\r\n");
      out.write("\t\tconsole.log(\"학생totCnt : \" + totCnt);\r\n");
      out.write("\r\n");
      out.write("\t\tvar paginationHtml = getPaginationHtml(currentPage, totCnt, pageSize,\r\n");
      out.write("\t\t\t\tpageBlocksize, 'stdSearch');\r\n");
      out.write("\r\n");
      out.write("\t\tconsole.log(currentPage);\r\n");
      out.write("\t\tconsole.log(totCnt);\r\n");
      out.write("\t\tconsole.log(pageSize);\r\n");
      out.write("\t\tconsole.log(pageBlocksize);\r\n");
      out.write("\r\n");
      out.write("\t\tconsole.log(\"학생paginationHtml : \" + paginationHtml);\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#EmpStdPagination\").empty().append(paginationHtml);\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#currentPage\").val(currentPage);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction std_Detail(std_id) {\r\n");
      out.write("\t\tconsole.log(\"id : \", std_id);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar param = {\r\n");
      out.write("\t\t\t\tstd_id : std_id,\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tconsole.log(\"param : \", param);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '/employ/stdDetail.do',\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdata : param,\r\n");
      out.write("\t\t\tasync : true,\r\n");
      out.write("\t\t\tdataType : \"text\",\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#lecList\").empty().append(data);\r\n");
      out.write("\t\t\t\t/* gfModalPop(\"#layer1\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tinit(data.std_info);\r\n");
      out.write("\t\t\t\tlistEmpStd(data.std_info); */\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(error) {\r\n");
      out.write("\t\t\t\tconsole.log(error)\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction listEmpStd(data) {\r\n");
      out.write("\t\tconsole.log(\"listEmpStd\", data);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#listEmpStd').empty();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#listEmpStd').append(data);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/** 유저 단건 조회 */\r\n");
      out.write("\tfunction fstd_info(std_id) {\r\n");
      out.write("\t\tconsole.log(\"std_id : \", std_id);\r\n");
      out.write("\t\t$(\"#std_id\").val(std_id);\r\n");
      out.write("\t\t// $(\"#rstdval\").val(loginID);\r\n");
      out.write("\r\n");
      out.write("\t\tvar param = {\r\n");
      out.write("\t\t\t\tstd_id : std_id\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tvar resultCallback = function(data) {\r\n");
      out.write("\t\t\tfstd_info_result(data);\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\t\tcallAjax(\"/employ/stdInfoDetail.do\", \"post\", \"json\", true, param,\r\n");
      out.write("\t\t\t\tresultCallback);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/** 유저 단건 조회 콜백 함수*/\r\n");
      out.write("\tfunction fstd_info_result(data) {\r\n");
      out.write("\t\tconsole.log(\"유저 단건 조회 콜백 함수 : \", data);\r\n");
      out.write("\r\n");
      out.write("\t\tif (data.result == \"SUCCESS\") {\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 모달 팝업\r\n");
      out.write("\t\t\tgfModalPop(\"#layer1\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t// 그룹코드 폼 데이터 설정\r\n");
      out.write("\t\t\tfInit_std(data.std_detail);\r\n");
      out.write("\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(data.resultMsg);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/** 학생 정보출력  */\r\n");
      out.write("\tfunction fInit_std(object) {\r\n");
      out.write("\t\tconsole.log(\"fInit : \", object);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#loginID\").val(object[0].std_id);\r\n");
      out.write("\t\t$(\"#std_num\").val(object[0].std_num);\r\n");
      out.write("\t\t$(\"#std_name\").val(object[0].name);\r\n");
      out.write("\t\t$(\"#tel\").val(object[0].tel);\r\n");
      out.write("\t\t$(\"#sex\").val(object[0].sex);\r\n");
      out.write("\t\t$(\"#mail\").val(object[0].mail);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* if(object.addr != null){\r\n");
      out.write("\t\t\t$(\"#std_addr\").text(object.addr.replace(/,/gi, \" \"));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#std_mail\").text(object.mail); */\r\n");
      out.write("\r\n");
      out.write("\t\tstd_Detail(object[0].std_id);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 등록 모달 팝업 하는 함수\r\n");
      out.write("\tfunction modify(std_id, action) {\r\n");
      out.write("\t\tconsole.log(\"loginID : \" , std_id);\r\n");
      out.write("\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '/employ/stdinfo.do',\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tstd_id : std_id,\r\n");
      out.write("\t\t\t\taction : action\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tasync : true,\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tconsole.log(\"등록 모달 데이터\" ,data);\r\n");
      out.write("\t\t\t\tinit(data.stdinfo, action);\r\n");
      out.write("\t\t\t\t$(\"#lecList\").empty().append(data);\r\n");
      out.write("\t\t\t\t/* gfModalPop(\"#layer1\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tinit(data.std_info);\r\n");
      out.write("\t\t\t\tlistEmpStd(data.std_info); */\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(error) {\r\n");
      out.write("\t\t\t\tconsole.log(error)\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t// layer1 을 모달 팝업 -> 닫기\r\n");
      out.write("\t\tgfModalPop(\"#layerB\");\r\n");
      out.write("\t\t//Close();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction init(data, action) {\r\n");
      out.write("\t\tconsole.log(\"init 값 확인 : \", data);\r\n");
      out.write("\t\tconsole.log(\"action : \", action);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(action == \"I\") {\r\n");
      out.write("\t\t\t$(\"#loginID\").val(data.loginID);\r\n");
      out.write("\t\t\t$(\"#stdName\").val(data.name);\r\n");
      out.write("\t\t\t$(\"#stdtel\").val(data.tel);\r\n");
      out.write("\t\t\t$(\"#comp_Name\").val(\"\"); \r\n");
      out.write("\t\t\t$(\"#employ_day\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#resign_day\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#action\").val(\"I\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(action == \"U\"){\r\n");
      out.write("\t\t\t$(\"#loginID\").val(data.loginID);\r\n");
      out.write("\t\t\t$(\"#stdName\").val(data.name);\r\n");
      out.write("\t\t\t$(\"#stdtel\").val(data.tel);\r\n");
      out.write("\t\t\t$(\"#comp_Name\").val(data.comp_name); \r\n");
      out.write("\t\t\t$(\"#employ_day\").val(data.employ_day);\r\n");
      out.write("\t\t\t$(\"#resign_day\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#action\").val(\"U\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction btn_employ() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// vaildation 체크\r\n");
      out.write("\t\tif (!fValidate_empInfo()) {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tconsole.log($(\"#comp_Name\").val());\r\n");
      out.write("\t\tconsole.log(\"loginId : \", std_id);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '/employ/stdEmploy.do',\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tstd_id : $(\"#loginID\").val(),\r\n");
      out.write("\t\t\t\tcomp_name : $(\"#comp_Name\").val(),\r\n");
      out.write("\t\t\t\temploy_day : $(\"#employ_day\").val(),\r\n");
      out.write("\t\t\t\tresign_day : $(\"#resign_day\").val(),\r\n");
      out.write("\t\t\t\taction : $(\"#action\").val()\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tasync : true,\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\tbtn_employ_result(data);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//$(\"#listEmpStd\").empty().append(data);\r\n");
      out.write("\t\t\t\t/* gfModalPop(\"#layer1\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tinit(data.std_info);\r\n");
      out.write("\t\t\t\tlistEmpStd(data.std_info); */\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(error) {\r\n");
      out.write("\t\t\t\tconsole.log(error)\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction btn_employ_result(data) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar currentPage = \"1\";\r\n");
      out.write("\t\tconsole.log(\"여기 탔나\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif (data.result == \"SUCCESS\") {\r\n");
      out.write("\t\t\talert(data.resultMsg);\r\n");
      out.write("\t\t\tgfCloseModal();\r\n");
      out.write("\t\t\tfListEmp(); \r\n");
      out.write("\t\t\tstdSearch();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//계획서 저장 validation \r\n");
      out.write("\tfunction fValidate_empInfo() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar chk = checkNotValue(\r\n");
      out.write("\t\t\t\t[ \r\n");
      out.write("\t\t\t\t  \t[ \"comp_Name\", \"회사명을 선택해주세요.\" ]\r\n");
      out.write("\t\t\t\t]\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t)\r\n");
      out.write("\t\tvar cnk = checkNotEmpty(\r\n");
      out.write("\t\t\t\t[\r\n");
      out.write("\t\t\t\t \t[ \"employ_day\", \"입사일을 적어주세요.\"]\r\n");
      out.write("\t\t\t\t ]\t\t\r\n");
      out.write("\t\t)\r\n");
      out.write("\r\n");
      out.write("\t\t if (!chk) {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t if (!cnk) {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 취업 목록 삭제\r\n");
      out.write("\tfunction delete_emp(std_id) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar param = {\r\n");
      out.write("\t\t\t\tstd_id : std_id\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '/employ/delEmploy.do',\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdata : param,\r\n");
      out.write("\t\t\tasync : true,\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t\talert(result.resultMsg);\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\tfListEmp($(\"#currentPage\").val());\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(error) {\r\n");
      out.write("\t\t\t\tconsole.log(error)\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form id=\"myForm\" action=\"\" method=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"action\" name=\"action\" value=\"\" /> <input\r\n");
      out.write("\t\t\ttype=\"hidden\" id=\"std_id\" name=\"std_id\" value=\"\" /> <input\r\n");
      out.write("\t\t\ttype=\"hidden\" id=\"currentPage\" name=\"currentPage\" value=\"1\" />\r\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"tmp_user\" name=\"loginID\" value=\"\"> \r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 모달 배경 -->\r\n");
      out.write("\t\t<div id=\"mask\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"wrap_area\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h2 class=\"hidden\">header 영역</h2>\r\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h2 class=\"hidden\">컨텐츠 영역</h2>\r\n");
      out.write("\t\t\t<div id=\"container\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"lnb\">\r\n");
      out.write("\t\t\t\t\t\t<!-- lnb 영역 --> ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/lnbMenu.jsp", out, false);
      out.write(" <!--// lnb (메뉴) 영역 -->\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"contents\">\r\n");
      out.write("\t\t\t\t\t\t<!-- contents -->\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"hidden\">contents 영역</h3> <!-- content -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"Location\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"../employ/employmentInfo.do\" class=\"btn_set home\">메인으로</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"btn_nav bold\">취업관리</span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn_nav bold\">취업 정보 관리 </span> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"../employ/employmentInfo.do\" class=\"btn_set refresh\">새로고침</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"conTitle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span>취업목록</span> <span class=\"fr\"> <!-- searchbar --> <select\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"searchKey\" name=\"searchKey\" style=\"width: 80px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"all\" id=\"all\" selected=\"selected\">전체</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"name\" id=\"name\">학생명</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"comp_name\" id=\"comp_name\">회사명</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select> <input type=\"text\" id=\"searchInfo\" name=\"searchInfo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"\" style=\"height: 28px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- // searchbar --> <!-- button --> <a class=\"btnType blue\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"\" name=\"searchEnter\" id=\"searchEnter\"><span>검색</span></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"employList\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"25%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">학번</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">학생명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">연락처</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">입사일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">퇴사일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">회사명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">재직여부</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">수정/삭제</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody id=\"listEmp\"></tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"paging_area\" id=\"Pagination\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"margin-bottom: 50px;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"EmpStd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"conTitle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>학생정보</span> <span class=\"fr\"> <!-- searchbar --> <select\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"searchKey1\" name=\"searchKey1\" style=\"width: 80px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"all1\" id=\"all1\" selected=\"selected\">전체</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"t_name\" id=\"t_name\">학생명</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"lec_nm\" id=\"lec_nm\">강의명</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select> <input type=\"text\" id=\"searchInfo1\" name=\"searchInfo1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"\" style=\"height: 28px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- // searchbar --> <!-- button --> <a class=\"btnType blue\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"\" name=\"searchEnter1\" id=\"searchEnter1\"><span>검색</span></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"div_std_list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<table class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<col width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<col width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<col width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">학번</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">학생명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">연락처</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">강의명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">가입일자</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">등록</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<tbody id=\"listEmpStd\"></tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"paging_area\" id=\"EmpStdPagination\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!--// content -->\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"hidden\">풋터 영역</h3>\r\n");
      out.write("\t\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"layer1\" class=\"layerPop layerType2\" style=\"width: 600px;\">\r\n");
      out.write("\t\t<dl>\r\n");
      out.write("\t\t\t<dt>\r\n");
      out.write("\t\t\t\t<strong>학생 정보</strong>\r\n");
      out.write("\t\t\t</dt>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<dd class=\"content\">\r\n");
      out.write("\t\t\t\t<!-- s : 여기에 내용입력 -->\r\n");
      out.write("\t\t\t\t<table class=\"row\">\r\n");
      out.write("\t\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" class=\"inputTxt p100\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"loginID\" name=\"loginID\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">학번</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" class=\"inputTxt p100\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"std_num\" name=\"std_num\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">이름</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" class=\"inputTxt p100\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"std_name\" name=\"std_name\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">전화 번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" class=\"inputTxt p100\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"tel\" name=\"tel\" /></td>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">성별</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" class=\"inputTxt p100\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"sex\" name=\"sex\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">이메일</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" class=\"inputTxt p100\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"mail\" name=\"mail\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"conTitle mt50\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span>수강 내역</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<table class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"30%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">강의ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">강의명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">기간</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<th scope=\"col\">상태</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody id=\"lecList\"></tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t\t<a href=\"\" class=\"closePop\"><span class=\"hidden\">닫기</span></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<!-- 취업 등록  -->\r\n");
      out.write("\t\t<form id=\"employ_form\">\r\n");
      out.write("\t\t<div id=\"layerB\" class=\"layerPop layerType2\" style=\"width: 600px;\">\r\n");
      out.write("\t\t<input type=\"hidden\" value=\"\" name=\"std_id\" id=\"rstdval\">\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t<strong>취업 등록</strong>\r\n");
      out.write("\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<dd class=\"content\">\r\n");
      out.write("\t\t\t\t\t<!-- s : 여기에 내용입력 -->\r\n");
      out.write("\t\t\t\t\t<table class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"30%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"30%\">\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">학생명</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=3><input type=\"text\" class=\"inputTxt p100\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"stdName\" id=\"stdName\" readonly /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">회사명 <span class=\"font_red\">*</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"10\"><input type=\"text\" class=\"inputTxt p100\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"comp_Name\" id=\"comp_Name\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">연락처</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" class=\"inputTxt p100\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"stdtel\" id=\"stdtel\"  readonly /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">입사일 <span class=\"font_red\">*</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" class=\"inputTxt p100\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"employ_day\" id=\"employ_day\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">퇴사일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" class=\"inputTxt p100\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"resign_day\" id=\"resign_day\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<!-- e : 여기에 내용입력 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"btn_areaC mt30\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\" class=\"btnType blue\" id=\"btn_employ\" name=\"btn\"><span>등록</span></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\" class=\"btnType gray\" id=\"btnClose\" name=\"btn\"><span>닫기</span></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t<a href=\"\" class=\"closePop\"><span class=\"hidden\">닫기</span></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /WEB-INF/view/employ/employ.jsp(6,0) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${now}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/view/employ/employ.jsp(6,0) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy.MM.dd");
      // /WEB-INF/view/employ/employ.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setVar("nowDate");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvar_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }
}
