/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2024-07-19 04:58:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.dashboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboardMgr_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/C:/Users/user/git/egov/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/scm/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/user/git/egov/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/scm/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1717304976992L));
    _jspx_dependants.put("jar:file:/C:/Users/user/git/egov/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/scm/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/view/dashboard/Order.jsp", Long.valueOf(1721360771071L));
    _jspx_dependants.put("/WEB-INF/view/dashboard/Notice.jsp", Long.valueOf(1721360731938L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<title>Job Korea</title>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/common_include.jsp", out, false);
      out.write("\r\n");
      out.write("<!-- <script src=\"https://unpkg.com/axios@0.12.0/dist/axios.min.js\"></script>\r\n");
      out.write("<script src=\"https://unpkg.com/lodash@4.13.1/lodash.min.js\"></script> -->\r\n");
      out.write("<!-- D3 -->\r\n");
      out.write("<style>\r\n");
      out.write("//\r\n");
      out.write("click-able rows\r\n");
      out.write("\t.clickable-rows {tbody tr td { cursor:pointer;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".el-table__expanded-cell {\r\n");
      out.write("\tcursor: default;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    // AJAX 요청으로 target.jsp 파일 가져오기\r\n");
      out.write("   /*  $.ajax({\r\n");
      out.write("        url: \"/WEB-INF/view/dashboard/Notice.jsp\",\r\n");
      out.write("        type: \"GET\",\r\n");
      out.write("        dataType: \"html\",\r\n");
      out.write("        success: function(response) {\r\n");
      out.write("            // 응답에서 필요한 부분 추출\r\n");
      out.write("            var content = $(response).find(\".content\").html();\r\n");
      out.write("            // #mainContent div에 추가\r\n");
      out.write("            $(\"#mainContent\").html(content);\r\n");
      out.write("        },\r\n");
      out.write("        error: function(xhr, status, error) {\r\n");
      out.write("            console.error(\"AJAX 오류 발생:\", error);\r\n");
      out.write("        }\r\n");
      out.write("    }); */\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form id=\"myForm\" action=\"\" method=\"\">\r\n");
      out.write("\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"currentPage\" value=\"1\"> <input\r\n");
      out.write("\t\t\ttype=\"hidden\" id=\"selectedInfNo\" value=\"\">\r\n");
      out.write("\t\t<!-- 모달 배경 -->\r\n");
      out.write("\t\t<div id=\"mask\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"wrap_area\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h2 class=\"hidden\">컨텐츠 영역</h2>\r\n");
      out.write("\t\t\t<div id=\"container\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li class=\"lnb\">\r\n");
      out.write("\t\t\t\t\t\t<!-- lnb 영역 --> ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/lnbMenu.jsp", out, false);
      out.write(" <!--// lnb 영역 -->\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"contents\">\r\n");
      out.write("\t\t\t\t\t\t<!-- contents -->\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"hidden\">contents 영역</h3> <!-- content -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"content\" style=\"margin-bottom: 20px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"Location\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"../dashboard/dashboard.do\" class=\"btn_set home\">메인으로</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"btn_nav bold\">메인</span> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\thref=\"../dashboard/dashboard.do\" class=\"btn_set refresh\">새로고침</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t <div id=\"mainContent\">\r\n");
      out.write("        \t\t\t\t\t\t<!-- target.jsp의 #content 부분이 여기 추가됩니다 -->\r\n");
      out.write("        \t\t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t\t</div>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/common_include.jsp", out, false);
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"/order/orderList.do\",\r\n");
      out.write("\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : function(response) {\r\n");
      out.write("\t\t\t\tvar orderList = response.oList; // 서버에서 반환된 주문 목록 배열\r\n");
      out.write("\t\t\t\tvar html = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t// 주문 목록 배열을 순회하며 테이블 행 생성\r\n");
      out.write("\t\t\t\torderList.forEach(function(order) {\r\n");
      out.write("\t\t\t\t\thtml += \"<tr>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td>\" + order.seq + \"</td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td>\" + order.product_name + \"</td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td>\" + order.order_count + \"</td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"<td>\" + order.order_date + \"</td>\";\r\n");
      out.write("\t\t\t\t\thtml += \"</tr>\";\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t// 생성된 HTML을 테이블에 추가\r\n");
      out.write("\t\t\t\t$(\"#orderDetail\").html(html);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr, status, error) {\r\n");
      out.write("\t\t\t\tconsole.error(\"AJAX 오류 발생:\", error);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<p class=\"conTitle\">\r\n");
      out.write("\t\t\t<span>주문 목록</span>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<table class=\"col\">\r\n");
      out.write("\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t<col width=\"50px\">\r\n");
      out.write("\t\t\t\t\t<col width=\"200px\">\r\n");
      out.write("\t\t\t\t\t<col width=\"60px\">\r\n");
      out.write("\t\t\t\t\t<col width=\"50px\">\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">주문 ID</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">상품 이름</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">상품 수량</th>\r\n");
      out.write("\t\t\t\t\t\t<th scope=\"col\">주문 일자</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody id=\"orderDetail\">\r\n");
      out.write("\t\t\t\t\t<!-- 주문 목록이 여기 추가됩니다 -->\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/common_include.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\r\n");
      out.write("\tvar pageSize = 5;\r\n");
      out.write("\tvar pageBlockPage = 10;\r\n");
      out.write("\t\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tnoticeSearch();\r\n");
      out.write("\t\tregisterBtnEvent();\r\n");
      out.write("\t\tfilePreview();\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\tfunction registerBtnEvent(){\r\n");
      out.write("\t\t$(\"#searchBtn\").click(function(e){\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\tnoticeSearch();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"a[name=btn]\").click(function(e){\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar btnId = $(this).attr(\"id\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tswitch(btnId){\r\n");
      out.write("\t\t\t\tcase \"btnSaveNotice\":\r\n");
      out.write("\t\t\t\t\tsaveNotice();\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"btnUpdateNotice\":\r\n");
      out.write("\t\t\t\t\tupdateNotice();\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"btnDeleteNotice\":\r\n");
      out.write("\t\t\t\t\tdeleteNotice();\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"btnClose\":\r\n");
      out.write("\t\t\t\t\tgfCloseModal();\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"btnSavefile\":\r\n");
      out.write("\t\t\t\t\tsaveFileNotice();\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"btnUpdatefile\":\r\n");
      out.write("\t\t\t\t\tupdateFileNotice();\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"btnDeletefile\":\r\n");
      out.write("\t\t\t\t\tdeleteFileNotice();\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction noticeSearch(cpage){\r\n");
      out.write("\t\tcpage = cpage || 1;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 공지사항 데이터 보여주는 로직\r\n");
      out.write("\t\tvar param = {\r\n");
      out.write("\t\t\t\tsearchTitle : $(\"#searchTitle\").val(),\r\n");
      out.write("\t\t\t\tsearchStDate : $(\"#searchStDate\").val(),\r\n");
      out.write("\t\t\t\tsearchEdDate : $(\"#searchEdDate\").val(),\r\n");
      out.write("\t\t\t\tcurrentPage : cpage,\r\n");
      out.write("\t\t\t\tpageSize : pageSize\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar callBackFunction = function(response){\r\n");
      out.write("\t\t\t$(\"#noticeList\").empty().append(response);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar pagieNavigateHtml = getPaginationHtml(cpage, $(\"#totcnt\").val(), pageSize, pageBlockPage, \"noticeSearch\")\r\n");
      out.write("\t\t\t$(\"#pagingNavi\").empty().append(pagieNavigateHtml);\r\n");
      out.write("\t\t\t$(\"#currentPage\").val(cpage);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcallAjax(\"/board/noticeList.do\", \"post\", \"text\", false, param, callBackFunction);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction insertModal(){\r\n");
      out.write("\t\t// 모달 열어주는 함수\r\n");
      out.write("\t\t$(\"#loginId\").val(\"\");\r\n");
      out.write("\t\t$(\"#noticeTitle\").val(\"\");\r\n");
      out.write("\t\t$(\"#noticeContent\").val(\"\");\r\n");
      out.write("\t\t$(\"#noticeSeq\").val(\"\");\r\n");
      out.write("\t\t$(\"#btnUpdateNotice\").hide();\r\n");
      out.write("\t\t$(\"#btnSaveNotice\").show();\r\n");
      out.write("\t\t$(\"#btnDeleteNotice\").hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tgfModalPop(\"#noticeInsertModal\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction saveNotice(){\r\n");
      out.write("\t\tif(!fValidate()){\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar param = {\r\n");
      out.write("\t\t\t\ttitle : $(\"#noticeTitle\").val(),\r\n");
      out.write("\t\t\t\tcontent : $(\"#noticeContent\").val(),\r\n");
      out.write("\t\t\t\tnoticeSeq: $(\"#noticeSeq\").val()\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar callBackFunction = function(response){\r\n");
      out.write("\t\t\tif(response.result == \"success\"){\r\n");
      out.write("\t\t\t\talert(\"저장이 되었습니다\");\r\n");
      out.write("\t\t\t\tgfCloseModal();\r\n");
      out.write("\t\t\t\tnoticeSearch();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcallAjax(\"/board/noticeSave.do\", \"post\", \"json\", false, param, callBackFunction);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction updateNotice(){\r\n");
      out.write("\t\tif(!fValidate()){\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar param = {\r\n");
      out.write("\t\t\t\ttitle : $(\"#noticeTitle\").val(),\r\n");
      out.write("\t\t\t\tcontent : $(\"#noticeContent\").val(),\r\n");
      out.write("\t\t\t\tnoticeSeq: $(\"#noticeSeq\").val()\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar callBackFunction = function(response){\r\n");
      out.write("\t\t\tif(response.result == \"success\"){\r\n");
      out.write("\t\t\t\talert(\"수정이 되었습니다\");\r\n");
      out.write("\t\t\t\tgfCloseModal();\r\n");
      out.write("\t\t\t\tnoticeSearch($(\"#currentPage\").val());\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcallAjax(\"/board/noticeUpdate.do\", \"post\", \"json\", false, param, callBackFunction);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction noticeDetailModal(seq){\r\n");
      out.write("\t\tvar param = {\r\n");
      out.write("\t\t\t\tnoticeSeq: seq\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar callBackFunction = function(data){\r\n");
      out.write("\t\t\tvar detail = data.detailValue;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#loginId\").val(detail.loginID);\r\n");
      out.write("\t\t\t$(\"#noticeTitle\").val(detail.noti_title);\r\n");
      out.write("\t\t\t$(\"#noticeContent\").val(detail.noti_content);\r\n");
      out.write("\t\t\t$(\"#noticeSeq\").val(detail.noti_seq);\r\n");
      out.write("\t\t\t$(\"#noticeContent\").val(detail.noti_content);\r\n");
      out.write("\t\t\t$(\"#noticeSeq\").val(detail.noti_seq);\r\n");
      out.write("\t\t\t$(\"#btnUpdateNotice\").show();\r\n");
      out.write("\t\t\t$(\"#btnSaveNotice\").hide();\r\n");
      out.write("\t\t\t$(\"#btnDeleteNotice\").show();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tgfModalPop(\"#noticeInsertModal\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcallAjax(\"/board/noticeDetail.do\", \"post\", \"json\", false, param, callBackFunction);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tfunction deleteNotice(){\r\n");
      out.write("\t\tvar param = {\r\n");
      out.write("\t\t\t\tnoticeSeq: $(\"#noticeSeq\").val()\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar callBackFunction = function(data){\r\n");
      out.write("\t\t\tif(data.result == \"success\"){\r\n");
      out.write("\t\t\t\talert(\"삭제 되었습니다\");\r\n");
      out.write("\t\t\t\tgfCloseModal();\r\n");
      out.write("\t\t\t\tnoticeSearch();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcallAjax(\"/board/noticeDelete.do\", \"post\", \"json\", false, param, callBackFunction);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fValidate() {\r\n");
      out.write("\t\tvar chk = checkNotEmpty(\r\n");
      out.write("\t\t\t\t[\r\n");
      out.write("\t\t\t\t\t\t[ \"noticeTitle\", \"제목를 입력해 주세요.\" ]\r\n");
      out.write("\t\t\t\t\t,\t[ \"noticeContent\", \"내용을 입력해 주세요\" ]\r\n");
      out.write("\t\t\t\t]\r\n");
      out.write("\t\t);\r\n");
      out.write("\t\tif (!chk) {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t// ------------------------------파일 기능 -----------------------------------------------------//\r\n");
      out.write("\tfunction insertFileModal(){\r\n");
      out.write("\t\t$(\"#loginId\").val(\"\");\r\n");
      out.write("\t\t$(\"#fileTitle\").val(\"\");\r\n");
      out.write("\t\t$(\"#fileContent\").val(\"\");\r\n");
      out.write("\t\t$(\"#noticeSeq\").val(\"\");\r\n");
      out.write("\t\t$(\"#btnUpdatefile\").hide();\r\n");
      out.write("\t\t$(\"#btnSavefile\").show();\r\n");
      out.write("\t\t$(\"#btnDeletefile\").hide();\r\n");
      out.write("\t\t$(\"#preview\").empty();\r\n");
      out.write("\t\t$(\"#fileInput\").val(\"\")\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tgfModalPop(\"#filePopUp\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction filePreview(){\r\n");
      out.write("\t\t$(\"#fileInput\").change(function(e){\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 파일이 있는 경우\r\n");
      out.write("\t\t\tif($(this)[0].files[0]){\r\n");
      out.write("\t\t\t\tvar fileInfo = $(\"#fileInput\").val();\r\n");
      out.write("\t\t\t\tvar fileInfoSplit = fileInfo.split(\".\");\r\n");
      out.write("\t\t\t\tvar fileLowerCase = fileInfoSplit[1].toLowerCase();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar imgPath = \"\";\r\n");
      out.write("\t\t\t\tvar previewHtml = \"\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(fileLowerCase == \"jpg\" || fileLowerCase == \"gif\" || fileLowerCase == \"png\"){\r\n");
      out.write("\t\t\t\t\t// 파일이 이미지 일 경우\r\n");
      out.write("\t\t\t\t\timgPath = window.URL.createObjectURL($(this)[0].files[0]);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tpreviewHtml = \"<img src='\" + imgPath + \"' id='imgFile' style='width: 100px; height: 100px;' />\";\t\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t// 파일이 이미지가 아닌 다른 것일 경우\r\n");
      out.write("\t\t\t\t\tpreviewHtml = \"\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#preview\").empty().append(previewHtml)\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fValidatefile() {\r\n");
      out.write("\t\tvar chk = checkNotEmpty(\r\n");
      out.write("\t\t\t\t[\r\n");
      out.write("\t\t\t\t\t\t[ \"fileTitle\", \"제목를 입력해 주세요.\" ]\r\n");
      out.write("\t\t\t\t\t,\t[ \"fileContent\", \"내용을 입력해 주세요\" ]\r\n");
      out.write("\t\t\t\t]\r\n");
      out.write("\t\t);\r\n");
      out.write("\t\tif (!chk) {\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 파일 저장\r\n");
      out.write("\tfunction saveFileNotice(){\r\n");
      out.write("\t\tif(!fValidatefile()){\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar getForm = document.getElementById(\"noticeForm\");\r\n");
      out.write("\t\tgetForm.entype = 'multipart/form-data';\r\n");
      out.write("\t\tvar fileData = new FormData(getForm);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar callBackFunction = function(data){\r\n");
      out.write("\t\t\tif(data.result == \"success\"){\r\n");
      out.write("\t\t\t\talert(\"저장이 되었습니다\");\r\n");
      out.write("\t\t\t\tgfCloseModal();\r\n");
      out.write("\t\t\t\tnoticeSearch();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcallAjaxFileUploadSetFormData(\"/board/noticeSaveFile.do\", \"post\", \"json\", false, fileData, callBackFunction);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction noticeDetailFileModal(noticeSeq){\r\n");
      out.write("\t\tvar param = {\r\n");
      out.write("\t\t\t\tnoticeSeq : noticeSeq\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar callBackFunction = function(data){\r\n");
      out.write("\t\t\t$(\"#noticeSeq\").val(data.detailValue.noti_seq);\r\n");
      out.write("\t\t\tdetailModalSetting(data.detailValue);\r\n");
      out.write("\t\t\tgfModalPop(\"#filePopUp\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcallAjax(\"/board/noticeDetail.do\", \"post\", \"json\", false, param, callBackFunction);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction detailModalSetting(detail){\r\n");
      out.write("\t\t// 상세조회 => 파일이 있을 경우(이미지) => 미리보기\r\n");
      out.write("\t\tif(detail != null){\r\n");
      out.write("\t\t\t$(\"#fileTitle\").val(detail.noti_title);\r\n");
      out.write("\t\t\t$(\"#fileContent\").val(detail.noti_content);\r\n");
      out.write("\t\t\t$(\"#btnSavefile\").hide();\r\n");
      out.write("\t\t\t$(\"#btnUpdatefile\").show();\r\n");
      out.write("\t\t\t$(\"#btnDeletefile\").show();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(detail.file_name != null){\r\n");
      out.write("\t\t\t\tvar ext = detail.file_ext.toLowerCase();\r\n");
      out.write("\t\t\t\tvar imagePath = \"\";\r\n");
      out.write("\t\t\t\tvar previewHtml = \"\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(ext == \"jpg\" || ext == \"gif\" || ext == \"png\"){\r\n");
      out.write("\t\t\t\t\timagePath = detail.logical_path;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tpreviewHtml = \"<a href='javascript:download()'>\";\r\n");
      out.write("\t\t\t\t\tpreviewHtml += \"<img src='\" + imagePath + \"' id='imgFile' style='width: 100px; height: 100px;' />\";\t\r\n");
      out.write("\t\t\t\t\tpreviewHtml += \"</a>\";\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tpreviewHtml = \"<a href='javascript:download()'>\";\r\n");
      out.write("\t\t\t\t\tpreviewHtml += detail.file_name;\r\n");
      out.write("\t\t\t\t\tpreviewHtml += \"</a>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#preview\").empty().append(previewHtml);\r\n");
      out.write("\t\t\t\t$(\"#fileInput\").val(\"\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction updateFileNotice(){\r\n");
      out.write("\t\tif(!fValidatefile()){\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar getForm = document.getElementById(\"noticeForm\");\r\n");
      out.write("\t\tgetForm.entype = 'multipart/form-data';\r\n");
      out.write("\t\tvar fileData = new FormData(getForm);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar callBackFunction = function(data){\r\n");
      out.write("\t\t\tif(data.result == \"success\"){\r\n");
      out.write("\t\t\t\talert(\"저장이 되었습니다\");\r\n");
      out.write("\t\t\t\tgfCloseModal();\r\n");
      out.write("\t\t\t\tnoticeSearch($(\"#currentPage\").val());\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcallAjaxFileUploadSetFormData(\"/board/noticeUpdateFile.do\", \"post\", \"json\", false, fileData, callBackFunction);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction deleteFileNotice(){\r\n");
      out.write("\t\tvar param = {\r\n");
      out.write("\t\t\t\tnoticeSeq: $(\"#noticeSeq\").val()\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar callBackFunction = function(data){\r\n");
      out.write("\t\t\tif(data.result == \"success\"){\r\n");
      out.write("\t\t\t\talert(\"삭제 되었습니다\");\r\n");
      out.write("\t\t\t\tgfCloseModal();\r\n");
      out.write("\t\t\t\tnoticeSearch();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcallAjax(\"/board/noticeDelete.do\", \"post\", \"json\", false, param, callBackFunction);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 파일 다운로드\r\n");
      out.write("\tfunction download(){\r\n");
      out.write("\t\tvar noticeSeq = $(\"#noticeSeq\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar params = \"<input type='hidden' name='noticeSeq' value='\"+ noticeSeq +\"' />\";\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"<form action='noticeDownload.do' method='post' id='fileDownload'>\" + params + \"</form>\"\r\n");
      out.write("\t\t).appendTo('body').submit().remove();\r\n");
      out.write("\t}\r\n");
      out.write("</script> \r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- contents -->\r\n");
      out.write("\t\t\t\t\t<h3 class=\"hidden\">contents 영역</h3> <!-- content -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<p class=\"conTitle\">\r\n");
      out.write("\t\t\t\t\t\t<span>공지사항</span> \r\n");
      out.write("\t\t\t\t\t\t<span class=\"fr\">\t\t\t\t\t\r\n");
      out.write(" \t                         \t 제목\r\n");
      out.write("                          <input type=\"text\" id=\"searchTitle\" name=\"searchTitle\" style=\"height: 25px; margin-right: 10px;\"/>\r\n");
      out.write("                          \t기간\r\n");
      out.write("                          <input type=\"date\" id=\"searchStDate\" name=\"searchStDate\" style=\"height: 25px; margin-right: 10px;\"/> \r\n");
      out.write("                          ~ \r\n");
      out.write("                          <input type=\"date\" id=\"searchEdDate\" name=\"searchEdDate\" style=\"height: 25px; margin-right: 10px;\"/>\r\n");
      out.write("\t\t\t\t\t\t  <a class=\"btnType red\" href=\"\" name=\"searchbtn\"  id=\"searchBtn\"><span>검색</span></a>\r\n");
      out.write("\t\t\t\t\t\t  <a class=\"btnType blue\" href=\"javascript:insertModal();\" name=\"modal\"><span>신규</span></a>\r\n");
      out.write("\t\t\t\t\t\t  <a class=\"btnType blue\" href=\"javascript:insertFileModal();\" name=\"modal\"><span>신규(파일)</span></a>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</p> \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"divNoticeList\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"col\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\t\t                            <colgroup>\r\n");
      out.write("\t\t\t\t\t\t                   <col width=\"50px\">\r\n");
      out.write("\t\t\t\t\t\t                   <col width=\"200px\">\r\n");
      out.write("\t\t\t\t\t\t                    <col width=\"60px\">\r\n");
      out.write("\t\t\t\t\t\t                   <col width=\"50px\">\r\n");
      out.write("\t\t\t\t\t                 </colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t              <th scope=\"col\">공지 번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t              <th scope=\"col\">공지 제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t              <th scope=\"col\">공지 날짜</th>\r\n");
      out.write("\t\t\t\t\t\t\t              <th scope=\"col\">작성자</th>\r\n");
      out.write("\t\t\t\t\t\t\t              \r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody id=\"noticeList\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- 갯수가 0인 경우  -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 갯수가 있는 경우  -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 이거 중간에 있으면 table 안먹힘  -->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t      \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t  <input type=\"hidden\" id=\"totcnt\" name=\"totcnt\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${noticeCnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 페이징 처리  -->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"paging_area\" id=\"pagingNavi\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"hidden\">풋터 영역</h3>\r\n");
      out.write("\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/view/common/footer.jsp", out, false);
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t<!-- 모달팝업 -->\r\n");
      out.write("\t<div id=\"noticeInsertModal\" class=\"layerPop layerType2\" style=\"width: 600px;\">\r\n");
      out.write("\t\t<dl>\r\n");
      out.write("\t\t\t<dt>\r\n");
      out.write("\t\t\t\t<strong>공지사항</strong>\r\n");
      out.write("\t\t\t</dt>\r\n");
      out.write("\t\t\t<dd class=\"content\">\r\n");
      out.write("\t\t\t\t<!-- s : 여기에 내용입력 -->\r\n");
      out.write("\t\t\t\t<table class=\"row\">\r\n");
      out.write("\t\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">작성자 <span class=\"font_red\">*</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" class=\"inputTxt p100\" name=\"loginId\" id=\"loginId\" readonly=\"readonly\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <th scope=\"row\">작성일<span class=\"font_red\">*</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" class=\"inputTxt p100\" name=\"write_date\" id=\"write_date\" /></td> -->\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">제목 <span class=\"font_red\">*</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"text\" class=\"inputTxt p100\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"noticeTitle\" id=\"noticeTitle\" /></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th scope=\"row\">내용</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea class=\"inputTxt p100\" name=\"noticeContent\" id=\"noticeContent\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- e : 여기에 내용입력 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"btn_areaC mt30\">\r\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"btnType blue\" id=\"btnSaveNotice\" name=\"btn\"><span>저장</span></a> \r\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"btnType blue\" id=\"btnUpdateNotice\" name=\"btn\" style=\"display:none\"><span>수정</span></a> \r\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"btnType blue\" id=\"btnDeleteNotice\" name=\"btn\"><span>삭제</span></a> \r\n");
      out.write("\t\t\t\t\t<a href=\"\"\tclass=\"btnType gray\"  id=\"btnClose\" name=\"btn\"><span>취소</span></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</dd>\r\n");
      out.write("\r\n");
      out.write("\t\t</dl>\r\n");
      out.write("\t\t<a href=\"\" class=\"closePop\"><span class=\"hidden\">닫기</span></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 모달 파일 팝업 --------------------------->\r\n");
      out.write("\t<form id=\"noticeForm\" action=\"\" method=\"\">\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"noticeSeq\" name=\"noticeSeq\" value=\"\">\r\n");
      out.write("\t\t<div id=\"filePopUp\" class=\"layerPop layerType2\" style=\"width: 600px;\">\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t<strong>공지사항 관리(파일)</strong>\r\n");
      out.write("\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t<dd class=\"content\">\r\n");
      out.write("\t\t\t\t\t<!-- s : 여기에 내용입력 -->\r\n");
      out.write("\t\t\t\t\t<table class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<caption>caption</caption>\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"120px\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"*\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"120px\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"*\">\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">제목 <span class=\"font_red\">*</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=3><input type=\"text\" class=\"inputTxt p100\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"fileTitle\" id=\"fileTitle\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">내용 <span class=\"font_red\">*</span></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><textarea name=\"fileContent\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"fileContent\" cols=\"40\" rows=\"5\"> </textarea></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">파일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"3\"><input type=\"file\" class=\"inputTxt p100\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"fileInput\" id=\"fileInput\" /></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th scope=\"row\">미리보기</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"preview\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- e : 여기에 내용입력 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"btn_areaC mt30\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\" class=\"btnType blue\" id=\"btnSavefile\" name=\"btn\"><span>저장</span></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\" class=\"btnType blue\" id=\"btnUpdatefile\" name=\"btn\"><span>수정</span></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\" class=\"btnType blue\" id=\"btnDeletefile\" name=\"btn\"><span>삭제</span></a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\" class=\"btnType gray\" id=\"btnClose\" name=\"btn\"><span>취소</span></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t<a href=\"\" class=\"closePop\"><span class=\"hidden\">닫기</span></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write(" \t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/view/dashboard/Notice.jsp(410,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${noticeCnt eq 0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<td colspan=\"4\">데이터가 존재하지 않습니다.</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/view/dashboard/Notice.jsp(418,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${noticeCnt > 0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fset_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write(" \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/view/dashboard/Notice.jsp(419,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("nRow");
      // /WEB-INF/view/dashboard/Notice.jsp(419,10) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/dashboard/Notice.jsp(419,10) '${pageSize*(currentPage-1)}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageSize*(currentPage-1)}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/view/dashboard/Notice.jsp(420,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/dashboard/Notice.jsp(420,10) '${notice}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${notice}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/view/dashboard/Notice.jsp(420,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("list");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t    <td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.noti_seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td><a href=\"javascript:noticeDetailFileModal(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.noti_seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.noti_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.noti_date}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list.loginID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- List에 있는 js 함수 호출가능 이거 그대로 가지고 가기 때문에 !!  -->\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t ");
            if (_jspx_meth_c_005fset_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write(" \r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/view/dashboard/Notice.jsp(430,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("nRow");
      // /WEB-INF/view/dashboard/Notice.jsp(430,12) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/dashboard/Notice.jsp(430,12) '${nRow + 1}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${nRow + 1}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }
}
